### ISSUE TITLE
deal.II Release 9.2.0 (released 2020/05/20)

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#10072]
<b>Release [9.2.0](https://github.com/dealii/dealii/releases/tag/v9.2.0)</b>
===
 - [generated documentation](https://dealii.43-1.org/documentation/9.2.0)

Check list for [release-tasks](https://github.com/dealii/release-papers/blob/master/release-tasks)
===

Release preparation steps:
--

- [x] <b>-3</b>  Send out notice to the mailinglist if anyone has outstanding issues or patches. (@drwells)
- [x] <b>-2</b>  Check all issues and pull-request on github. Create a list of things to fix before the release. (@kronbichler, #9729)
- [x] <b>-1</b>  Update the list of publications. (Send standard e-mail)
- [x] <b>-1a</b> Start release paper process with email to all current (principal) developers
- [x] <b>-1b</b> Update the authors list on the homepage authors.html (@tamiko, mailmap: #10140)
- [x] <b>-1c</b> Update the list of contributors in the release paper (@tamiko)
- [x] <b>0</b>   Do some basic testing as always (@tamiko, #10073)
- [x] <b>0a</b>  Rerun cppcheck across the source files (@drwells #10107)
- [x] <b>0b</b>  Check for doxygen formatting problems @tjhei 
- [x] <b>0c</b>  Fix formatting bugs reported by various command line queries @tjhei #10094
- [x] <b>0d</b>  Check that doxygen produces no errors when generating offline docs. @tjhei 
- [x] <b>0e</b>  Run the copyright script @tjhei  #10097
- [x] <b>0f</b>  Update Trilinos and PETSc to the latest release on the tester and update documentation of supported version. (@tamiko, #10141)
- [x] <b>0g</b>  Run codespell (@drwells, #10075)

Prerelease/Release steps:
--
- [x] <b>*</b>   Nominate a "release officer" that is in charge of (almost all) of the following steps
- [x] <b>1</b>   Create new changes file
- [x] <b>1a</b>  Adjust doc/users/doxygen.html to link to the to-be-created TAG file.
- [x] <b>4</b>   Create a release branch
- [x] <b>5</b>   Update the VERSION from 9.2.0-pre to 9.3.0-pre on master (see the discussion below)
- [x] <b>6</b>   Update the official tester to test on the release branch dealii-9.2
- [x] <b>6a</b>  On mainline, update deal.II dependencies of examples
- [x] <b>7</b>   Create an AUTHORS file
- [x] <b>7a</b>  Send prerelease announcement to dealii@googlegroups.com
- [x] <b>8</b>   Remove unfinished tutorial programs.
- [x] <b>9</b>   Write up a short release note and save it as announce-9.2
- [x] <b>9a</b>  Write the release paper
- [x] <b>10</b>  Test the branch thoroughly
- [x] <b>10a</b> Do the same for the code gallery examples (@drwells)
- [x] <b>11</b>  Create documentation and verify
- [x] <b>11a</b> Check that .gitattributes is up to date. (Do quick tests work?)
- [x] <b>12</b>  Push the button
    - Change VERSION to 9.2.0 for a release and to 9.2.0-rc1 for a pre-release
    - Create a signed tag of exactly this commit
    - Push changes to github
- [x] <b>13</b>  Create the tar files
    - Download the source tarball from github, verify that its contents is what we expect
    - Cryptographically sign it (detached, armored signature)
    - Create full offline_doc tarball and sign it
- [x] <b>14a</b> Create a pre-release on github and upload files (and detached signatures)

Post-release steps:
--
- [x] <b>15</b>  Generate the documentation on the webserver.
- [x] <b>16</b>  Adjust header.include on homepage
- [x] <b>17a</b> Ask Luca for Mac packages
- [x] <b>17b</b> Update dealii in [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py)
- [x] <b>17c</b> Update dealii in candi (@tjhei)
- [x] <b>17d</b> Update dealii in [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/dealii)
- [ ] <b>17e</b> Update dealii in [Ubuntu/Debian](https://salsa.debian.org/science-team/deal.ii)
- [ ] <b>17f</b> Update dealii in [Archlinux AUR](https://aur.archlinux.org/packages/deal-ii/) (@drwells)
- [x] <b>17g</b> Update dealii virtualbox images (@tjhei)
- [x] <b>18</b>  Finish writing the announcement
- [x] <b>18b</b> Adjust news.html in the deal.II homepage repo
- [x] <b>19</b>  Announce the release via e-mail
- [x] <b>19a</b> Send a note to the Facebook and Google+ accounts
- [x] <b>19b</b> Update the deal.II wikipedia page (@tjhei)
- [x] <b>19d</b> Send thank-you email and list the people already referenced in step -1b above
- [x] <b>20</b>  Celebrate!

**Comment by tamiko** [comment]
@bangerth This should have been issue number 10000 :smile_cat:

**Comment by drwells** [comment]
Do we want to increment to 10.0.0 after this release? We discussed this on the call today and, if I recall correctly, no one explicitly opposed it.

**Comment by bangerth** [comment]
Ha, yes, *that* would have deserved the 10,000!

I wasn't on the call at that point (sorry, guys) but once we bump to 10.0.pre, you can't go back to 9.3.pre any more if we decide that the next release isn't worth the major version number upgrade. My preference would be to stick with the 9.x scheme unless we have a good reason to actually *want* a new major version number. (I suspect that you *had* a good reason -- anyone want to share?)

**Comment by tjhei** [comment]
> we have a good reason to actually _want_ a new major version number.

We were chatting about some bigger changes that might happen after this release (merge hp and non-hp dofhandler, bigger linear algebra changes, etc.). This might justify breaking a few things and calling it a new major release.

But I agree, we should bump to 9.3.pre because this allows us to delay this decision.

**Comment by tjhei** [comment]
I can confirm that we now build cleanly with:
```
Intel 18.0.3.20180410
Intel 19.0.5.20190815
Intel 19.1.0.20200306
```

**Comment by tamiko** [comment]
> I can confirm that we now build cleanly with:
> ```
> Intel 18.0.3.20180410
> Intel 19.0.5.20190815
> Intel 19.1.0.20200306
> ```

I have just set up 19.1.1.217 on bob. Compilation succeeds - the test
results of the dozen tests I ran scared me. I will enable the variant
for the next test run.

**Comment by tjhei** [comment]
> the test results of the dozen tests I ran scared me

Yeah, there have been really scary incorrect optimizations in the past. Do you want to share some to look into?

**Comment by tamiko** [comment]
@tjhei The testsuite (aka bob) should be done in about 8-10h. We will have a detailed testsuite run then.

**Comment by tamiko** [comment]
@tjhei https://cdash.43-1.org/buildSummary.php?buildid=6316 - this doesn't look good.

**Comment by tjhei** [comment]
Wow, those are some interesting problems. Lots of different stuff!

**Comment by tjhei** [comment]
It is slow because we use ld, I think.

**Comment by tjhei** [comment]
So, something is wrong with your configuration as all MPI related tests fail. On my machine, many of the tests pass (I haven't done a whole run though).

**Comment by drwells** [comment]
I'm working on the bounding box failure.

**Comment by tamiko** [comment]
@drwells Hold your horses on that one - I think we're good for all sensible compilers.

**Comment by tamiko** [comment]
@tjhei Well then, would you mind to shed some light what "on my machine" precisely means? You did recompile the whole dependency tree with icc?

**Comment by tamiko** [comment]
@dealii/dealii All, I think we reached a very good state to branch off and tag an rc1. I suggest we wait for #7513 (which is reasonably self contained) and we tag afterwards. We can selectively cherry pick to the release branch afterwards. I suggest we extend the "merge window" by one day to Wednesday next week (because we tag one day earlier).

**Comment by drwells** [comment]
@tamiko Would you prefer that we ignore these failures on the release branch?

**Comment by drwells** [comment]
(You're right that it's not a big deal - I just want to see what your plan is).

**Comment by tamiko** [comment]
@drwells As @tjhei pointed out the test failures above are very likely at least in part also an issue with the environment in the container (I did install icc into my gcc-8 container and did not check whether the openmpi version installed in the container is actually compatible, etc.). My call is to ignore this test result and tag the rc1 now in order to have a known release candidate that everyone can test individually as well.

**Comment by tamiko** [comment]
@tjhei The build actually uses ld.gold (icc supports that at least in the lastest version). :smile:

**Comment by tjhei** [comment]
> Well then, would you mind to shed some light what "on my machine" precisely means?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
$ . ~/bin/intel/parallel_studio_xe_2020/psxevars.sh
Intel(R) Parallel Studio XE 2020 Update 1 for Linux*
Copyright (C) 2009-2020 Intel Corporation. All rights reserved.
heister@heister-haidebao ~ $ icpc -v
icpc version 19.1.1.217 (gcc version 7.5.0 compatibility)
$ mpicxx -v
mpicxx for MPICH version 3.3a2
$ g++ -v
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
```
dependencies compiled with gcc.

**Comment by tamiko** [comment]
@tjhei Merci!

**Comment by tjhei** [comment]
- [ ] cherry-pick #10161

**Comment by tjhei** [comment]
Jenkins CI status of the branch:
Linux: [![Build Status](https://jenkins.tjhei.info/job/dealii/job/dealii-9.2/badge/icon)](https://jenkins.tjhei.info/job/dealii/job/dealii-9.2/)
OSX: [![Build Status](https://jenkins.tjhei.info/job/dealii-OSX/job/dealii-9.2/badge/icon)](https://jenkins.tjhei.info/job/dealii-OSX/job/dealii-9.2/)
tidy: [![Build Status](https://jenkins.tjhei.info/job/dealii-tidy/job/dealii-9.2/badge/icon)](https://jenkins.tjhei.info/job/dealii-tidy/job/dealii-9.2/)

**Comment by tjhei** [comment]
Wait, who checked "celebration" and celebrated without me? :-) 

Thanks, @tamiko and @kronbichler for your hard work over the last couple of weeks!
