### ISSUE TITLE
Hide `hp_capability_enabled` parameter

### ISSUE THREAD

**Issue by marcfehling** [dealii/dealii#11102]
The huge effort of merging both DoFHandlers in  #10328 introduced a parameter `hp_capability_enabled` to still distinguish between both functionalities.

We can actually hide this parameter entirely from the interface and make it private: Depending on which kind of finite element is associated with the DoFHandler, we can set the `hp_capability_enabled` variable accordingly. It will be false for `FiniteElement` or `hp::FECollection` of length 1, and `true` for `hp::FECollection` of length > 1.

I will come up with a patch soon and figure out whether it works. We should make this part of the 9.3 release as this parameter has been introduced since the last release.

---

EDIT: I decided to split solving this issue in multiple PRs:
- [x] #11123 Hide `hp_capability_enabled` parameter.
- [x] #11133 Rework interface to `Triangulation` signals.
- [x] #11160 Slim interface for `DoFHandler` initialization.
- [x] #11149 Simplify `DoFHandler::distribute_dofs`.
- [x] #11220 Deprecate `DoFHandlerType` template argument.
- [x] #11153 Avoid using deprecated DoFHandler functions.

**Comment by marcfehling** [comment]
While preparing a patch for this issue, I must admit that I am not happy with the current interface.

The characteristics of the `DoFHandler` depend on the type of the registered `Triangulation` and the length of the registered `FECollection`. In my opinion, we should only allow to register both simultaneously.

Right now, we have a zoo of functions (which evolved over time) to register them separately:
```
DoFHandler::DoFHandler()
DoFHandler::DoFHandler(tria)
DoFHandler::set_fes(fes)
DoFHandler::initialize(tria, fes)
DoFHandler::distribute_dofs(fes)
```

I would like to propose a reduced set of functions:
```
DoFHandler::DoFHandler()
DoFHandler::DoFHandler(tria, fes)   [internally calls set(tria, fes)]
DoFHandler::set(tria, fes)
DoFHandler::enumerate_dofs()
```
This would result in one single possibility to change both `Triangulation` and `FECollection` at once via `set(tria, fes)`.

However, this would be a fundamental change to the interface, and nearly every single deal.II user code would need to be adapted. Before starting to work on this patch and to deprecate the old interface, I would like to hear your honest opinion on this. :-)

**Comment by marcfehling** [comment]
While preparing a patch for this issue, I must admit that I am not happy with the current interface.

The characteristics of the `DoFHandler` depend on the type of the registered `Triangulation` and the length of the registered `FECollection`. In my opinion, we should only allow to register both simultaneously.

Right now, we have a zoo of functions (which evolved over time) to register them separately:
```
DoFHandler::DoFHandler()
DoFHandler::DoFHandler(tria)
DoFHandler::set_fes(fes)
DoFHandler::initialize(tria, fes)
DoFHandler::distribute_dofs(fes)
```

I would like to propose a reduced set of functions:
```
DoFHandler::DoFHandler()
DoFHandler::DoFHandler(tria, fes)   [internally calls set(tria, fes)]
DoFHandler::set(tria, fes)
DoFHandler::enumerate_dofs()
```
This would result in one single possibility to change both `Triangulation` and `FECollection` at once via `set(tria, fes)`.

However, this would be a fundamental change to the interface, and nearly every single deal.II user code would need to be adapted. Before starting to work on this patch and to deprecate the old interface, I would like to hear your honest opinion on this. :-)

**Comment by bangerth** [comment]
I wouldn't mind if the only interface that remains is `DoFHandler(tria)` and `DoFHandler::distribute_dofs(fe)`. Those are the functions used throughout the tutorials. I think the others can probably go.

**Comment by marcfehling** [comment]
@bangerth - I see one problem with leaving only these two functions: In hp applications, we most likely want to set `active_fe_indices` before calling `distribute_dofs`. We need to somehow tell the DoFHandler to switch in hp-mode before calling `distribute_dofs`.

Hmm, we could turn this around and allow setting `active_fe_indices` in the still undefined state of the `DoFHandler`. If just a single fe is passed to `distribute_dofs`, we'll specify the non-hp mode and then free the memory of `active_fe_indices`. If we end in hp mode, we'll check the validity of the `active_fe_indices` in `distribute_dofs`. Would you be okay with this approach?

**Comment by bangerth** [comment]
Yes, that makes sense. But do we have the data structures set up if we haven't called `distribute_dofs()` yet? That might be the problem @peterrum tried to solve...

**Comment by peterrum** [comment]
> Yes, that makes sense. But do we have the data structures set up if we haven't called distribute_dofs() yet? That might be the problem @peterrum tried to solve...

In contrary, I didn't (tried) to solve the problem. See: https://github.com/dealii/dealii/pull/10328#issuecomment-633212131 and https://github.com/dealii/dealii/pull/10328#issuecomment-643308328.

As stated there, I would be fine to allocate these data structures per default (also in non-hp case).

**Comment by marcfehling** [comment]
I decided to let every `DoFHandler` begin in hp-mode and then toggle it whenever necessary (see open pull request).

I will continue to slim the interface and simplify `DoFHandler::distribute_dofs` in follow-up PRs.

**Comment by marcfehling** [comment]
Do you have an idea how we can deprecate the `DoFHandlerType` template argument (as used by the `DataOut` and `SolutionTransfer` classes)?

In the future, there will only be one type of `DoFHandler` left. The only way I can come up with is to create copies of these classes without the `DoFHandlerType` template argument, and deprecate the old classes with the argument. Is this the way to go?

**Comment by peterrum** [comment]
@marcfehling I have collected here a list problematic places: https://github.com/dealii/dealii/issues/10333#issuecomment-648414341

**Comment by masterleinad** [comment]
> The only way I can come up with is to create copies of these classes without the `DoFHandlerType` template argument, and deprecate the old classes with the argument. Is this the way to go?

I would do something like https://godbolt.org/z/Gh7faj using template specialization and deriving the to be deprecated class (specialization) from the specialization using the default template parameter.

**Comment by marcfehling** [comment]
@masterleinad Thank you for your hint on partial template specialization!

However, I stumbled on a problem while realizing the deprecation. Currently, the `spacedim` template argument is hidden in the `DoFHandlerType` typename as a static member variable. We need that `spacedim` argument in these classes.

So ideally, code like the following should be possible, but I have no idea to realize that kind of 'template argument overloading'.
```
const unsigned int dim = 2, spacedim = 3;

SolutionTransfer<dim, DoFHandler<dim, spacedim>> st1;   // old code to be deprecated
SolutionTransfer<dim, spacedim> st2;                    // ideal new code
```

**Comment by masterleinad** [comment]
That's not possible. You can't overload a template class replacing a type by a non-type template parameter. In that case, we simply need a new name.

**Comment by marcfehling** [comment]
It looks like the only classes without a `spacedim` template arguement affected by this are `SolutionTransfer`, `DataOut` and `FEFieldFunction`.

It would not be too much work to change this in user code, so we could also consider confronting them with an incompatibility at the new release by dropping the `DoFHandlerType` template argument for these classes. Although I'm not happy about proposing this, I think it's still better to find new names (which also involves changing even more in documentation, examples etc).

**Comment by masterleinad** [comment]
> It would not be too much work to change this in user code, so we could also consider confronting them with an incompatibility at the new release by dropping the `DoFHandlerType` template argument for these classes. Although I'm not happy about proposing this, I think it's still better to find new names (which also involves changing even more in documentation, examples etc).

Yes, we can't just change the second template parameter. We always deprecate behavior before removing it. So I think new names is the only way to go (or we ignore it and continue to pass `DoFHandler<dim, spacedim>` instead of `spacedim` as second template parameter)
