### ISSUE TITLE
Unfinished tutorial programs

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#11998]
Let's have a list of programs that are around but not finished yet.

**To be merged for 9.3:**

- [ ] step-71: Intro to AD (#10392)
- [ ] step-72: step-15 with AD (#10393)
- [ ] step-73: Finite strain elasticity with AD (#10394)
- [ ] step-75: parallel hp functionality (#11254)
- [ ] step-76 (#11158)
- [ ] step-77: Using KINSOL for a nonlinear problem (#11953)
- [ ] step-??: The Black-Scholes equation (no PR yet, @tyand96)
- [ ] step-??: Topology optimization (no PR yet, @juleoc02)

**To be merged for later releases:**

**Comment by jppelteret** [comment]
Good idea to construct this list, @bangerth. Since I already moved the milestone for step-73, I took the liberty of shifting it to the "later" category in the list.

**Comment by tjhei** [comment]
There is also step-66, which has been open for an embarrassing long time. 😢 I think it might be too late for 9.3 but I am going through the major changes in the next few days.

**Comment by gfcas** [comment]
we updated #8229 to #12201. I try to commit a brief results section until Monday.

**Comment by tjhei** [comment]
@vyushut and I are working on a tutorial for TraceFEM building on step-85, can we have step-90?

**Comment by webwurli** [comment]
Regarding step-92:

I've been working on documenting source-codes from my 2024 workshop presentation in Fort Collins and can offer to share:

- 3 python scripts for generating step-file based models
    - conductor-example.py
    - ModelComposer.py
    - occ_converter.py
    
    The meshing is done utilizing gmsh (python API).
    
- solvers (documentation still quite lousy - sorry for that - I'm working on it):
    - electrostatic (Laplace)
    - magnetostatic (curl curl A = %my J)
    - full wave (time-harmonic/complex valued)
    
    Actually, those solvers are parallelized using MPI (PETSc) and MUMPS direct solver
    I'm working on matrix-free implementations.
    (actually only running for electrostatic)
    
- documetation of the field equations implemented in aboce solvers (LibreOffice document)
    
I have following concerns:
- As you can see: I'm not finished in transforming all this into something ready to present as tutorial.
  E.g.: an html web-page is still missing. (Maybe all this is to much for compressing it into a tutorial?? But it belongs together. The solvers at least need that conductor-example mesh.)
- Is there a "playground" to share it with you that interested guys/ladies can do some testing, give feedback, re-fine the "tutorial" concept, bug-fixing ??
  because: I think it's still not in a quality to push into dealii tutorials main repository.

- Better make a contribution to the code-gallery instead ??

Thank You for your feedback.

Best Regards,
Stephan

**Comment by bangerth** [comment]
@webwurli Feel free to open a dedicated issue here on github for the discussion of this specific program. You can also just open a pull request that adds that program -- that allows others to download the files and play with them, and push their own changes. We often go around many times with comments and fixes for tutorial program pull requests.

**Comment by cembooks** [comment]
Hello, 

I am working on a new tutorial. It illustrates application of the FE_Nedelec and FE_RaviartThomas finite elements to problems in electromagnetics. It solves curl-curl equation. It is almost ready. I would like to reserve a number for my new tutorial so I can use it in PR. I see that the next tutorial must be step-97. Am I right? Can I reserve this number for my new tutorial?

Kind regard,
Siarhei

**Comment by bangerth** [comment]
@cembooks I reserved step-97 for you in the list at the top of this github issue. If you wanted, we can also give you step-94, which currently also seems unallocated.

**Comment by cembooks** [comment]
Thanks! Step-97 sounds good!

**Comment by cembooks** [comment]
Hello,

I am working on a new tutorial. It is a two-dimensional version of step-97. May I have a number for the new tutorial? 

Kind regards,
Siarhei

**Comment by bangerth** [comment]
@cembooks I gave you step-98. I think that would make for a good sequence with 97.

**Comment by cembooks** [comment]
> [@cembooks](https://github.com/cembooks) I gave you step-98. I think that would make for a good sequence with 97.

Thanks!

**Comment by tjhei** [comment]
My group is in the process of finishing up (maybe for the 9.8 release):
1. Matrix-based, parallel, GPU enabled Laplace solver using PETSc+hypre with low order rediscretization and matrix-free operator evaluation (Portable::MatrixFree): step-99
2. Portable::MatrixFree GMG for the Stokes equation on GPUs

I will reserve step-104 for the latter...

**Comment by cembooks** [comment]
Hello.

May I have a number for a new tutorial? The new tutorial illustrates application of the Nedelec and Raviart-Thomas finite elements on a locally refined mesh. It solves the eddy current problem in magnetoquasistatic approximation of Maxwell’s equations.

**Comment by bangerth** [comment]
@cembooks How about 105?

**Comment by cembooks** [comment]
@bangerth Thanks! 105 sounds good.
