### ISSUE TITLE
deal.II Release 9.3.0

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#12117]
[deal.II 9.3.0 Release Candidate 1](https://github.com/dealii/dealii/releases/tag/v9.3.0-rc1)
===

Check list for [release-tasks](https://github.com/dealii/release-papers/blob/master/release-tasks)
===

Release preparation steps:
--

- [x] <b>-3</b>  Send out notice to the mailinglist if anyone has outstanding issues or patches.
- [x] <b>-2</b>  Check all issues and pull-request on github. Create a list of things to fix before the release.
- [x] <b>-1</b>  Update the list of publications. (Send standard e-mail)
- [x] <b>-1a</b> Start release paper process with email to all current (principal) developers
- [x] <b>-1b</b> Update the authors list on the homepage authors.html
- [x] <b>-1c</b> Update the list of contributors in the release paper
- [x] <b>0</b>   Do some basic testing as always
- [x] <b>0a</b>  Rerun cppcheck across the source files (@drwells) (cppcheck didn't find anything worth fixing)
- [x] <b>0c</b>  Fix formatting bugs reported by various command line queries (@peterrum: looks alright although there are a number of warnings)
- [x] <b>0d</b>  Check that doxygen produces no errors when generating offline docs.
- [x] <b>0e</b>  Run the copyright script
- [x] <b>0f</b>  Update Trilinos and PETSc to the latest release on the tester and update documentation of supported version. (@tamiko testsuite updated; @drwells for PETSc)
- [x] <b>0g</b>  Run codespell (@drwells) (we should do this as late as possible since tutorials are still coming in) (#12238)

Release steps:
--

- [x] <b>*</b>   Nominate a "release officer" that is in charge of (almost all) of the following steps
- [x] <b>1</b>   Create new changes file (#12282)
- [x] <b>1a</b>  Adjust doc/users/doxygen.html to link to the to-be-created TAG file. (#12283)
- [x] <b>4</b>   Create a release branch
- [x] <b>5</b>   Update the VERSION from 9.3.0-pre to 10.0.0-pre on master (#12284)
- [x] <b>6</b>   Update the official tester to test on the release branch dealii-9.3
- [x] <b>6a</b>  On mainline, update deal.II dependencies of examples (#12285)
- [x] <b>7</b>   Create an AUTHORS file
- [x] <b>7a</b>  Send prerelease announcement to dealii@googlegroups.com
- [x] <b>8</b>   Remove unfinished tutorial programs.
- [x] <b>9</b>   Write up a short release note and save it as announce-9.3
- [x] <b>9a</b>  Write the release paper
- [x] <b>10</b>  Test the branch thoroughly
- [x] <b>10a</b> Do the same for the code gallery examples
- [x] <b>11</b>  Create documentation and verify
- [x] <b>11a</b> Check that .gitattributes is up to date. (Do quick tests work?)
- [x] <b>12</b>  Push the button
    - Change VERSION to 9.3.0 for a release and to 9.3.0-rc1 for a pre-release
    - Create a signed tag of exactly this commit
    - Push changes to github
- [x] <b>13</b>  Create the tar files
    - Download the source tarball from github, verify that its contents is what we expect
    - Cryptographically sign it (detached, armored signature)
    - Create full offline_doc tarball and sign it

Postrelease steps:
--

- [x] <b>14a</b> Create a pre-release on github and upload files (and detached signatures)
- [x] <b>15</b>  Generate the documentation on the webserver.
- [x] <b>16</b>  Adjust header.include on homepage
- [x] <b>17a</b> Ask Luca for Mac packages
- [x] <b>17b</b> Update dealii in [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py)
- [ ] <b>17c</b> Update dealii in [Candi](https://github.com/dealii/candi/blob/master/candi.cfg)
- [x] <b>17d</b> Update dealii in [Gentoo](https://gitweb.gentoo.org/proj/sci.git/tree/sci-libs/dealii)
- [x] <b>17e</b> Update dealii in [Ubuntu/Debian](https://salsa.debian.org/science-team/deal.ii) (@tamiko)
- [ ] <b>17f</b> Update dealii in [Archlinux AUR](https://aur.archlinux.org/packages/deal-ii/) (@drwells)
- [ ] <b>17g</b> Update dealii virtualbox images
- [x] <b>18</b>  Finish writing the announcement
- [x] <b>18b</b> Adjust news.html in the deal.II homepage repo
- [x] <b>19</b>  Announce the release via e-mail
- [x] <b>19a</b> Send a note to the Facebook and Google+ accounts
- [x] <b>19b</b> Update the deal.II wikipedia page
- [x] <b>19d</b> Send thank-you email and list the people already referenced in step -1b above
- [x] <b>20</b>  Celebrate!

**Comment by drwells** [comment]
I also volunteered to help triage issues tagged as 9.3.

**Comment by drwells** [comment]
If it helps, I have access to intel's compilers (16.0 - 20.2).

**Comment by tamiko** [comment]
@drwells Would you mind to run a quick build test with 16.0 and 20.2?

**Comment by drwells** [comment]
My intel compilers are all set up with my system copy of GCC, which is too old to compile the library - I'll see if I can work around it but it will take me some time.

**Comment by tjhei** [comment]
Does https://community.intel.com/t5/Intel-C-Compiler/Setting-gcc-version/td-p/1133403 work for you?

**Comment by drwells** [comment]
Partially - setting that and also overriding `LD_LIBRARY_PATH` worked. I'm not sure if this is an intel thing or if it's specific to the machine I'm on.

**Comment by drwells** [comment]
I might need some offline help in this but here's the current state of intel:
- intel 16.0 + GCC 6.3.0: cannot finish running CMake due to a non-constexpr `std::max`
- intel 17.2 + GCC 6.3.0: I get boost errors of the form
```
nas/longleaf/home/drwells/Documents/Code/CPP/dealii/bundled/boost-1.70.0/include/boost/core/noncopyable.hpp(46): error: defaulted default constructor cannot be constexpr because the corresponding implicitly declared default constructor would not be constexpr
        BOOST_CONSTEXPR noncopyable() = default;
```
that seems like a configuration bug on our part - `BOOST_CONSTEXPR` should not be `constexpr` with this compiler.
- intel 20.2 + GCC 9.1.0: seems to work - library and examples compile and link

**Comment by tjhei** [comment]
Jenkins build status: [![Build Status](https://jenkins.tjhei.info/buildStatus/icon?job=dealii%2Fdealii-9.3)](https://jenkins.tjhei.info/job/dealii/job/dealii-9.3/)

**Comment by Rombur** [comment]
Using the `main` branch of clang, I am getting warnings like this one:
```
/home/bruno/tmp/dealii-9.3.0-rc1/include/deal.II/grid/tria_accessor.h:755:3: warning: definition of implicit copy constructor for 'TriaAccessor<1, 2, 3>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
  operator=(const TriaAccessor &) = delete;
```
There are only a couple of places where we have this problem but it fills my screen of warnings. How do we want to deal with this? Should we add a flag to suppress the warnings or we hope that clang will fix this by the time of release?

**Comment by masterleinad** [comment]
I don't see a reason to not just provide defaulted special member functions.

**Comment by tamiko** [comment]
| Host | Configuration | Commit | Build errors | Build warnings | Failing tests | Passing tests |
| - | - | - | :-: | :-: | :-: | :-: |
| tester | [Clang-5.0.2-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1415) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1415) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1415) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1415) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1415) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1415) |
| tester | [Clang-4.0.1-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1417) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1417) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1417) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1417) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1417) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1417) |
| tester | [GNU-10.3.0-dealii-9.3-cpp20](https://cdash.43-1.org/buildSummary.php?buildid=1418) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1418) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1418) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1418) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1418) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1418) |
| tester | [GNU-9.3.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1419) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1419) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1419) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1419) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1419) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1419) |
| tester | [GNU-8.4.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1420) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1420) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1420) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1420) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1420) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1420) |
| tester | [GNU-7.4.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1421) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1421) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1421) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1421) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1421) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1421) |
| tester | [GNU-6.5.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1422) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1422) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1422) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1422) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1422) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1422) |
| tester | [GNU-7.5.0-dealii-9.3-ubuntu-lts-18](https://cdash.43-1.org/buildSummary.php?buildid=1423) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1423) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1423) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1423) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1423) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1423) |
| tester | [GNU-8.3.0-dealii-9.3-debian-10](https://cdash.43-1.org/buildSummary.php?buildid=1424) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1424) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1424) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1424) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1424) | [0](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1424) |
| tester | [Clang-12.0.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1426) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1426) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1426) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1426) | [19](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1426) | [12850](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1426) |
| tester | [GNU-11.1.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1427) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1427) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1427) | [228](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1427) | [13](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1427) | [12856](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1427) |
| tester | [GNU-10.3.0-dealii-9.3-autodetection](https://cdash.43-1.org/buildSummary.php?buildid=1430) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1430) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1430) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1430) | [7](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1430) | [12862](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1430) |
| tester | [GNU-9.3.0-dealii-9.3-ubuntu-lts-20](https://cdash.43-1.org/buildSummary.php?buildid=1433) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1433) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1433) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1433) | [9](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1433) | [12588](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1433) |
| tester | [GNU-10.2.1-dealii-9.3-debian-11](https://cdash.43-1.org/buildSummary.php?buildid=1435) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1435) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1435) | [250](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1435) | [7](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1435) | [12660](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1435) |
| tester | [Clang-12.0.0-dealii-9.3-avx2-O3](https://cdash.43-1.org/buildSummary.php?buildid=1437) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1437) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1437) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1437) | [17](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1437) | [12852](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1437) |
| tester | [Clang-12.0.0-dealii-9.3-avx2-Ofast](https://cdash.43-1.org/buildSummary.php?buildid=1439) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1439) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1439) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1439) | [59](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1439) | [12810](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1439) |
| tester | [GNU-10.3.0-dealii-9.3-avx2-O3](https://cdash.43-1.org/buildSummary.php?buildid=1440) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1440) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1440) | [4](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1440) | [13](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1440) | [12856](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1440) |
| tester | [GNU-10.3.0-dealii-9.3-64bit_indices](https://cdash.43-1.org/buildSummary.php?buildid=1441) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1441) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1441) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1441) | [1](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1441) | [12820](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1441) |
| tester | [GNU-10.3.0-dealii-9.3-minimal_bundled](https://cdash.43-1.org/buildSummary.php?buildid=1442) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1442) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1442) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1442) | [0](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1442) | [8406](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1442) |
| tester | [GNU-10.3.0-dealii-9.3-petsc_complex](https://cdash.43-1.org/buildSummary.php?buildid=1447) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1447) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1447) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1447) | [11](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1447) | [12524](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1447) |
| tester | [GNU-10.3.0-dealii-9.3-tets](https://cdash.43-1.org/buildSummary.php?buildid=1449) | [9124f4](https://cdash.43-1.org/viewUpdate.php?buildid=1449) | [0](https://cdash.43-1.org/viewBuildError.php?buildid=1449) | [0](https://cdash.43-1.org/viewBuildError.php?type=1&buildid=1449) | [5](https://cdash.43-1.org/viewTest.php?onlyfailed&buildid=1449) | [12261](https://cdash.43-1.org/viewTest.php?onlypassed&buildid=1449) |

**Comment by bangerth** [comment]
That looks reasonably good. Do we know what is going on with clang 12 on linux with the 59 failing tests?

**Comment by masterleinad** [comment]
> That looks reasonably good. Do we know what is going on with clang 12 on linux with the 59 failing tests?

That's a build using `-Ofast`.

**Comment by kronbichler** [comment]
On the news page as item 19 of the general improvements, we write:
```
New: The multithreading framework in the library has been completely revamped: Intel TBB has been replaced by taskflow, which is bundled within the library. Multithreading support is now unconditionally enabled and we removed the CMake option DEAL_II_WITH_THREADS. The tasking framework can be controlled using MultithreadInfo and the DEAL_II_NUM_THREADS environment variable.
(Wolfgang Bangerth, Timo Heister, Matthias Maier, 2020/05/25)
```
I guess this is not right for the current 9.3 release, so we should move this somewhere else?

**Comment by bangerth** [comment]
It's just not true. We should just remove this item.

**Comment by jppelteret** [comment]
I've opened a PR to update the spack package. See https://github.com/spack/spack/pull/24077/files

**Comment by tjhei** [comment]
documentation is online, so I updated the website header.

**Comment by tamiko** [comment]
@tjhei In the mood of sending the announcement e-mail? :-)

**Comment by tjhei** [comment]
Not tonight. Trying to work on candi stuff...

**Comment by tamiko** [comment]
With the announcement e-mails I'd say we're done here :partying_face:
