### ISSUE TITLE
Step 66 Update

### ISSUE THREAD

**Issue by gfcas** [dealii/dealii#12252]
A few outstanding ideas/issues to the recently merged tutorial step-66 (#8229, #12201, #12239)
- [x] Indention of code snippets in intro.dox (#12258)
- [x] Prevent doxygen from setting unwanted links (#13081)
- [x] Update phd citation after final publictaion (#13081)
- [x] Figures not displayed in online doc (#12258)
- ~~Cite Armijo rule for variable Newton step length~~
- ~~Mathematical background using zero initial value for newton_update in SolverCG~~
- [x] Add changelog entry for 9.3 (#12253)

**Comment by bangerth** [comment]
@gfcas Is there anything left that you'd like to get in before the 9.3 release, or can we remove the milestone?

**Comment by gfcas** [comment]
> 
> 
> @gfcas Is there anything left that you'd like to get in before the 9.3 release, or can we remove the milestone?

Let us drop the 9.3 flag, I will look for the rest in the near future after the release.

**Comment by bangerth** [comment]
There are still two open points in the list at the top of this issue. @gfcas -- any chance you could address these so we can close this issue?

**Comment by gfcas** [comment]
> There are still two open points in the list at the top of this issue. @gfcas -- any chance you could address these so we can close this issue?

I am very sorry for this. The explanation for the second point, wasn't that straightforward, I thought... and for the first point I realized that I previously used a bit different stepping instead of the Armijo rule. So I would rather remove these tasks from the list and close this issue ...

**Comment by bangerth** [comment]
OK, that's a useful outcome as well :-)
