### ISSUE TITLE
9.3.1 cherry-picking candidates

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#12494]
We have gotten a few bug reports since the release that may be worth cherry-picking:

- [x] MPI underlinkage: handled in #12488 
- [x] ExodusII should reorder elements: #12398 (#12519)
- [x] Segmentation faults in MappingQGeneric: #12468 (#12518)
- [x] Whatever fix makes both intel 19 and GCC 11 happy: WIP (#12507)
- [x] #12490 
- [ ] #12474
- [x] #12506, done in #12510 
- [x] #12505 done in #12509 
- [x] #12511 done in #12516
- [x] #12515 done in ##12524
- [x] #12523 done in #12525

If we end up testing a new release candidate it might be worthwhile to add a few of these in. If we find anything else we should add it to this issue.

**Comment by marcfehling** [comment]
There seems to be a compilation issue with `intel-18` as well, see https://github.com/xsdk-project/xsdk-issues/issues/148.
We should incorporate a fix for this in 9.3.1 as well.

**Comment by tjhei** [comment]
Also #12507 once we have a fix

**Comment by tamiko** [comment]
OK. I think everything we can meaningfully fixed is fixed. Tagging the release now.
