### ISSUE TITLE
deal.II Release 9.4 - post-release tasks

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#13574]
Release: [v9.4.0](https://github.com/dealii/dealii/releases/tag/v9.4.0)
===

For Release Candidate 1:
--
 - [x] remove `p4est_bug_01` test (#13998) 
 - [x] remove taskflow (#13999)

For Release Candidate 2:
--
 - [x] Fix compile warnings (#13910)
    - [x] Uninitialized warnings with avx2+: `GNU-12.1.0-master-avx2-O3` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2335) (#14027)
     - [x] Deprecated `Threads::thread` on debian: `GNU-10.2.1-master-debian-11 ` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2331)
 - [x] Fix failing tests on main configuration `GNU-12.1.0-master-autodetection` (#13703)
     - [ ] base/hdf5_03.mpirun=4.release
     - [ ] base/hdf5_05.mpirun=4.debug
     - [ ] base/hdf5_05.mpirun=4.release
     - [x] mpi/p4est_bug_01.debug (#13998)
     - [x] petsc/preconditioner_tvmult_01.mpirun=3.debug
     - [x] petsc/preconditioner_tvmult_01.mpirun=3.release
     - [x] symengine/batch_optimizer_09_1.release (#14003)
     - [x] symengine/step-44-sd-quadrature_level_01.debug
     - [x] symengine/step-44-sd-quadrature_level_01.release
     - [x] symengine/step-44-sd-quadrature_level_02.debug
     - [x] symengine/step-44-sd-quadrature_level_02.release
     - [x] symengine/step-44-sd-quadrature_level_03.debug
     - [x] symengine/step-44-sd-quadrature_level_03.release

For Release Candidate 3:
--
 - [x] Fix compile warnings (#13910)
     - [x] Deprecated `Threads::thread` on debian: `GNU-10.2.1-master-debian-11 ` [cdash](https://cdash.dealii.43-1.org/viewBuildError.php?type=1&buildid=2331) (#14036)
 - [x] Fix failing tests on main configuration `GNU-12.1.0-master-autodetection` (#13703)
     - [ ] base/hdf5_03.mpirun=4.release
     - [ ] base/hdf5_05.mpirun=4.debug
     - [ ] base/hdf5_05.mpirun=4.release
     - [x] petsc/preconditioner_tvmult_01.mpirun=3.debug (#14033)
     - [x] petsc/preconditioner_tvmult_01.mpirun=3.release (#14033)

Check list for [release-tasks](https://github.com/dealii/release-papers/blob/master/release-tasks)
=================================================================================

Release preparation steps:
--

- [x] <b>-3</b>  Send out notice to the mailinglist if anyone has outstanding issues or patches.
- [x] <b>-2</b>  Check all issues and pull-request on github. Create a list of things to fix before the release.
- [x] <b>-1</b>  Update the list of publications. (Send standard e-mail)
- [x] <b>-1a</b> Start release paper process with email to all current (principal) developers
- [x] <b>-1b</b> Update the authors list on the homepage authors.html
- [x] <b>-1c</b> Update the list of contributors in the release paper
- [x] <b>0</b>   Do some basic testing as always
- [x] <b>0a</b>  Rerun cppcheck across the source files
- [x] <b>0c</b>  Fix formatting bugs reported by various command line queries
- [x] <b>0d</b>  Check that doxygen produces no errors when generating offline docs.
- [x] <b>0e</b>  Run the copyright script (#13775)
- [x] <b>0f</b>  Update Trilinos and PETSc to the latest release on the tester and update documentation of supported version. (#13982)
- [x] <b>0g</b>  Run codespell (#13968)

Release steps:
--

- [x] <b>*</b>   Nominate a "release officer" that is in charge of (almost all) of the following steps
- [x] <b>1</b>   Create new changes file
- [x] <b>1a</b>  Adjust doc/users/doxygen.html to link to the to-be-created TAG file.
- [x] <b>4</b>   Create a release branch
- [x] <b>5</b>   Update the VERSION from 9.0.0-pre to 9.1.0-pre on master
- [x] <b>5a</b>  Convert `DEAL_II_DEPRECATED_EARLY` to `DEAL_II_DEPRECATED` on master
- [x] <b>6</b>   Update the official tester to test on the release branch dealii-9.0
- [x] <b>6a</b>  On mainline, update deal.II dependencies of examples
- [x] <b>7</b>   Create an AUTHORS file
- [x] <b>7a</b>  Send prerelease announcement to dealii@googlegroups.com
- [x] <b>8</b>   Remove unfinished tutorial programs.
- [x] <b>9</b>   Write up a short release note and save it as announce-9.0
- [x] <b>9a</b>  Write the release paper
- [x] <b>10</b>  Test the branch thoroughly
- [x] <b>10a</b> Do the same for the code gallery examples
- [x] <b>11</b>  Create documentation and verify
- [x] <b>11a</b> Check that .gitattributes is up to date. (Do quick tests work?)
- [x] <b>12</b>  Push the button
    - Change VERSION to 9.0.0 for a release and to 9.0.0-rc1 for a pre-release
    - Create a signed tag of exactly this commit
    - Push changes to github
- [x] <b>13</b>  Create the tar files
    - Download the source tarball from github, verify that its contents is what we expect
    - Cryptographically sign it (detached, armored signature)
    - Create full offline_doc tarball and sign it

Postrelease steps:
--

- [x] <b>14a</b> Create a pre-release on github and upload files (and detached signatures)
- [x] <b>15</b>  Generate the documentation on the webserver.
- [x] <b>16</b>  Adjust header.include on homepage
- [x] <b>17a</b> Ask Luca for Mac packages
- [x] <b>17b</b> Update dealii in [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py)
- [x] <b>17c</b> Update dealii in [Candi](https://github.com/dealii/candi/blob/master/candi.cfg)
- [x] <b>17d</b> Update dealii in [Gentoo](https://github.com/gentoo/gentoo/master/tree/sci-libs/dealii)
- [x] <b>17e</b> Update dealii in [Ubuntu/Debian](https://salsa.debian.org/science-team/deal.ii)
- [x] <b>17f</b> Update dealii in [Archlinux AUR](https://aur.archlinux.org/packages/deal-ii/)
- [ ] <b>17g</b> Update dealii virtualbox images
- [x] <b>18</b>  Finish writing the announcement
- [x] <b>18b</b> Adjust news.html in the deal.II homepage repo
- [x] <b>19</b>  Announce the release via e-mail
- [x] <b>19a</b> Send a note to the Facebook and Google+ accounts
- [x] <b>19b</b> Update the deal.II wikipedia page
- [x] <b>19d</b> Send thank-you email and list the people already referenced in step -1b above
- [x] <b>20</b>  Celebrate!

**Comment by drwells** [comment]
We should try to stick to a deadline for getting examples in: how about May 27?

**Comment by bangerth** [comment]
Unfinished tutorials: #11998.

**Comment by tamiko** [comment]
@luca-heltai *ping* I gently request Mac packages :-)

**Comment by tamiko** [comment]
@tjhei *ping* I would like to ask you to regenerate the Virtualbox image :-)

**Comment by tamiko** [comment]
@drwells Would you mind updating the AUR package? :-)

**Comment by tjhei** [comment]
I can only start with the VM once the release is done.

**Comment by tjhei** [comment]
Wait, you tagged 9.4.0 already?! Yay!

**Comment by luca-heltai** [comment]
During my intensive deal.II course, I managed to play a bit with an apple M1 mac, and got 95% of the packages working with spack. The only ones I did not manage were gmsh and oce. I will try to get access again to an M1 mac to build also an image for it. Later today I'll upload the Mac package for intel.

**Comment by blaisb** [comment]
> During my intensive deal.II course, I managed to play a bit with an apple M1 mac, and got 95% of the packages working with spack. The only ones I did not manage were gmsh and oce. I will try to get access again to an M1 mac to build also an image for it. Later today I'll upload the Mac package for intel (and @jppelteret opened a PR on spack [spack/spack#31279](https://github.com/spack/spack/pull/31279))

Very very cool @luca-heltai ! Looking forward to that.

**Comment by drwells** [comment]
If we ever do a 9.4.1 we should think about porting 

- #14044
- #14087
