### ISSUE TITLE
Multigrid for non-nested levels

### ISSUE THREAD

**Issue by peterrum** [dealii/dealii#15148]
PR #15141 introduces a two-level transfer operator between non-nested levels. There are some todos we need to tackle before merging that one and some follow-up tasks.

### TODO

- [ ] Add `RemotePointEvaluation::get_cell_data()`
- [ ] Allow `NonMatching::MappingInfo::reinit_cells()` to work on any containers.
- [ ] Introduce `MGTwoLevelTransferBase`.

### Follow-up tasks

- [ ] multiple components
- [ ] other types of elements, e.g., DG

FYI @fdrmrc

**Comment by jh66637** [comment]
I did this for DG in a different context and can give ``` other types of elements, e.g., DG``` a try. I will try to do it as soon as possible :)
