### ISSUE TITLE
Tracking deal.ii in downstream package repositories

### ISSUE THREAD

**Issue by luzpaz** [dealii/dealii#15957]
### Current snapshot of downstream package repos

<a href="https://repology.org/project/deal.ii/versions">
    <img src="https://repology.org/badge/vertical-allrepos/deal.ii.svg?columns=3" alt="Packaging status">
</a>

### TODO

- [ ] Debian & Ubuntu (in process)
- [ ] Homebrew Cask https://github.com/orgs/Homebrew/discussions/4765
- [ ] Macports (needs bump) https://trac.macports.org/ticket/68123#ticket

**Comment by tamiko** [comment]
@luzpaz Debian and Ubuntu are currently in the process of being upgraded. This is a slightly involved process.

**Comment by luzpaz** [comment]
@tamiko is there a link to where this is happening so it can be tracked ?

**Comment by luzpaz** [comment]
Homebrew packager having an issue with creating a formula for deal.ii (see https://github.com/orgs/Homebrew/discussions/4765#discussioncomment-10101347)
