### ISSUE TITLE
deal.II Release 9.6

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17202]
# Current release candidate: [v9.6.0-rc1](https://github.com/dealii/dealii/releases/tag/v9.6.0-rc1) 2024-07-24

## Pre-Release testing, QA and final code changes:

The following is a list of ouststanding QA tests that should be checked before proceeding with a release. In order to avoid duplicated efforts, add your a tag `@name` with your name after `assigned:` and link corresponding pull requests after `pr:`. Finally, tick of the box when the task is done.

 - [x] <b>Update regression tester</b> (assigned:, pr: @tamiko)
   Check and (if necessary) update testing infrastructure so that at least one configuration runs with the latest versions of external dependencies and compilers.
   Also temporarily remove all test exclusion lists from the regression tester and re-evaluate whether they still have to be excluded.
 - [x] <b>Outstanding issues and pull-requests</b>
   Check issues and pull-requests for outstanding fixes.
   Update release milestones https://github.com/dealii/dealii/milestone/14
 - [x] <b>cppcheck</b> (assigned:@masterleinad, pr:#17208)
   Run `cppcheck` across all source files:
   ```cppcheck --force -j4 --enable=all -I./include/ ./source/*/*.cc >cppcheck-results.txt 2>&1```
   and look for anything that should obviously be fixed.
 - [x] <b>codespell</b> (assigned: @marcfehling, pr: #17206)
   Run `codespell` across all source files:
   ```codespell ./contrib/ ./cmake/ ./doc/ ./examples/ ./include/ ./source/```
   and look for typos and spelling mistakes that should be fixed.
 - [x] <b>clang-tidy</b> (assigned:@masterleinad, pr:#17207)
   Run clang tidy via:
   ```mkdir build && cd build```
   ```../contrib/utilities/run_clang_tidy.sh ../```
   and check that no warnings are reported.
 - [x] <b>doxygen reflinks</b> (assigned:, pr: #17203)
   Check doxygen commands and reflinks:
   ```cd include```
   ```find . -iname "*h" -exec ../contrib/utilities/wrapcomments.py {} \; > /dev/null```
   Also check:
   ```grep -l '@ref[^"]*"[^"]*$' **/*.h```
   ```grep -l '@ref$' **/*.h```
   <b>NOTE:</b> Do not use wrapcomments.py to actually reflow comments - the script causes too much churn with little value.
 - [x] <b>doxygen</b> (assigned: @masterleinad, pr:#17237)
   Check that doxygen produces no errors when generating the documentation. Also check that the tutorial dot graph gets generated.
 - [x] <b>Copyright years</b> (assigned:@masterleinad, pr:https://github.com/dealii/dealii/pull/17227)
   Run the copyright script:
   ```./contrib/utilities/update-copyright```
   and make a pull request with a commit title "Update copyright years".
 - [x] <b>Examples </b> (assigned:@blaisb, pr:)
   Configure, build and run all examples by hand:
   ```cd examples```
   ```for i in step-* ; do (cd $i ; cmake -DDEAL_II_DIR=../.. . ; make ; make run) ; done```
   This step will require looking at the output and checking whether
   anything untoward is happening. 
   **BB:** Status: 1-90 Tested. Exceptions: {17,18,36,53,62,86} (can't compile PETSC on my manjaro machine). Following Issues are related to broken examples: #17409
 - [x] <b>Code Gallery</b> (assigned:, pr: &mdash;)
   Do the same for the code gallery examples: They should at the very least compile. If possible, also run them to make sure they don't trip up any exceptions.
 - [x] <b>Update `.gitattributes`</b> (assigned: @tamiko, pr: #17371)
       Check that `.gitattributes` is up to date by using `git archive` and checking that the contents is meaningful. In particular, do `quicktests` still run?
 - [x] <b>Update authors</b> (assigned: @tamiko, pr: https://github.com/dealii/old-website/pull/50)
   Update the authors list on the homepage authors.html by cross-referencing `doc/news/changes.h` and the git commit history:
   ```egrep '[0-9]+/[0-9]+/[0-9]+' doc/news/changes/*/* | perl -p -e 's/^.*\(//g; s#, *[0-9/]+\)##g; s/, */\n/g;' | sort | uniq```
   Compare with the git commit history between the last release and current master:
   ```git log --date=short --format="%an %aE" v9.4.0..HEAD | grep -v 'dependabot\[bot\]' | sort | uniq```
   The list of contributors to the current release should also be copied to the end of the release paper.
 - [x] <b>Changes file</b> (assigned: @tamiko, pr: #17375)
   This step should happen immediately before branching off so that the changes file does not need to get updated again.
   * Create a new changes files by running the following commands:
     ```mkdir build-doc && cd build-doc```
     ```cmake -DDOCUMENTATION=ON ../```
     ```make documentation```
     ```cp doc/news/changes.h ../doc/news/9.4.0-vs-9.5.0.h```
     ```cd ../```
   * Manually check `doc/news/9.4.0-vs-9.5.0.h` for dead links, duplicated entries, obsolete entries (e.g., commit 1 adds feature A, commit 2 fixes feature A), etc. Update `@page` title and copyright year.
   * Then,
     ```git checkout -b update-changes-file```
     ```git add  doc/news/9.4.0-vs-9.5.0.h```
     ```git commit -m "Update the changelog file for the release."```
     ```git rm doc/news/changes/{major,minor,incompatibilities}/*```
     ```git commit -m "Remove now obsolete files."```
     ```touch doc/news/changes/{major,minor,incompatibilities}/20230623dummy```
     ```git add doc/news/changes/{major,minor,incompatibilities}/20230623dummy```
     ```git commit -m "Add dummy files."```
   * Adjust `doc/users/doxygen.html` to link to the to-be-created TAG file.
   * Make a pull request

**Comment by tamiko** [comment]
## Branching off the release branch:

<i>tba</i>

**Comment by tamiko** [comment]
## Post-Branching tasks and cleanup:

<i>tba</i>

**Comment by bangerth** [comment]
Big patches that we should see if we can review and merge:
* #15540 
* #12429 
* #15706

**Comment by jpthiele** [comment]
I'm aware that #17183 is also quite large since it wraps all Tpetra counterparts to the previous Epetra Preconditioners apart from ML and MueLU, but it also adds quite a bit of functionality and usability for the new wrappers.
Especially since it is compatible with the iterative solvers of deal.II. 

From a functionality standpoint the PR is done (including documentation and tests)

**Comment by tamiko** [comment]
## Create a release:

The following steps have to be done by a single developer (with admin privileges on the [repository](https://github.com/dealii/dealii))

 - [ ] <b>Push the button</b>
   * Update `VERSION` file from `9.5.0-rc0` to `9.5.0-rc1` (or `9.5.0` for the final release):
     ```echo 9.5.0-rc1 > VERSION```
     ```git commit -a -m "update VERSION for release"```
     <b>Note:</b> This commit is done without a pull request! We use the `update VERSION` commits to tag releases and release candidates and therefore should be plain commit
s on the release branch.
   * Create a signed tag for the commit:
     ```git tag -s -m "deal.II Pre-Release Version 9.5.0-rc1" v9.5.0-rc1```
     or alternatively for a release:
     ```git tag -s -m "deal.II Version 9.5.0" v9.5.0```
     You need a working gnupg key for this. (You should have anyway :-P)
   * Push the changes to github (assuming `origin` points to github):
     ```git push origin dealii-9.5 v9.5.0-rc1```
 - [ ] <b>Create and sign tar archive</b>
   * Github automatically generates a source tarball from the current repository state, see https://github.com/dealii/dealii/releases
   * Download the source tarball from github, verify that its contents is what we expect, e.g., by doing the following in a clean repository:
     ```git checkout v9.5.0-rc1```
     ```tar --strip-components=1 -xvf dealii-9.5.0-rc1.tar.gz```
     ```git status```
     Now, the last git status will only record some deleted files but must not show any modified file contents!
   * Sign it:
     ```gpg --detach-sign --armor dealii-9.5.0-rc1.tar.gz```
 - [ ] <b>Create and sign documentation tar archive</b>
   * Check out the code-gallery at the correct path
   * Install MathJax locally and export the path, for example on Debian/Gentoo:
     ```export MATHJAX_ROOT="/usr/share/mathjax"```
   * Generate and install the documentation from a clean working directory containing the tagged release and configure with:
     ```cmake -DDOCUMENTATION=ON -DDEAL_II_DOXYGEN_USE_MATHJAX=ON -DDEAL_II_DOXYGEN_USE_ONLINE_MATHJAX=OFF \```
     ```      -DDEAL_II_COMPILE_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=<install>```
     ```make documentation```
     ```make examples```
   * Download images:
     ```<install>/doc/doxygen/deal.II```
     ```<source dir>/contrib/utilities/makeofflinedoc.sh```
   * (In the same directory) copy mathjax and fix includes:
     ```cp -r "$MATHJAX_ROOT" mathjax```
     ```sed -i -e "s#$MATHJAX_ROOT#mathjax#" **/*.html```
   * Grep the documentation for "full path leaks", for example grep for your user name and the git repository location and fix up all remaining locations (in particular deal.tag)
   * Create `dealii-9.5.0-rc1-offline_documentation.tar.gz`:
     ```cd <install>```
     ```tar --numeric-owner --owner=0 --group=0 -cvf dealii-9.5.0-rc1-offline_documentation.tar doc examples```
     ```gzip dealii-9.2.0-offline_documentation.tar```
   * And sign it:
     ```gpg --detach-sign --armor dealii-9.5.0-rc1-offline_documentation.tar.gz```
 - [ ] <b>Create a (pre-)release on github</b>
   * Got to https://github.com/dealii/dealii/tags and select the just uploaded v9.5.0-rc1 tag and click on "add release notes". Use the following information:
     ```Tag: v9.0.0-rc1 existing tag```
     ```Release title: deal.II pre-release version 9.0.0-rc1```
     ```Description: ""```
     <b>Note:</b> For a release use:
     ```Tag: dealii-9.5.0 existing tag```
     ```Release title: deal.II version 9.5.0```
     ```Description: [Short version of release notes as found in announce-9.5]```
     ```A full list of changes can be found at```
     ```https://www.dealii.org/developer/doxygen/deal.II/changes_between_9_4_0_and_9_5_0.html```
   * Attach `dealii-9.5.0-rc1.tar.gz` (yes, once again), `dealii-9.5.0-rc1.tar.gz.asc`, `dealii-9.5.0-rc1-offline_documentation.tar.gz`, `dealii-9.5.0-rc1-offline_documentation.tar.gz.asc`.

**Comment by tamiko** [comment]
The testsuite results for rc1 are very promising:

| Host | Configuration | Commit | Build errors | Build warnings | Failing tests | Passing tests |
| - | - | - | :-: | :-: | :-: | :-: |
| tester-voyager | [GNU-10.2.1-dealii-9.6-debian-11](https://cdash.dealii.org/buildSummary.php?buildid=944) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=944) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=944) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=944) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=944) | [42](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=944) |
| tester-voyager | [GNU-11.4.0-dealii-9.6-ubuntu-lts-22.04](https://cdash.dealii.org/buildSummary.php?buildid=945) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=945) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=945) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=945) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=945) | [46](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=945) |
| tester-voyager | [GNU-9.4.0-dealii-9.6-ubuntu-lts-20.04](https://cdash.dealii.org/buildSummary.php?buildid=946) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=946) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=946) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=946) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=946) | [46](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=946) |
| tester-voyager | [GNU-13.3.0-dealii-9.6-debian-13](https://cdash.dealii.org/buildSummary.php?buildid=948) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=948) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=948) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=948) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=948) | [15804](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=948) |
| tester-voyager | [GNU-12.2.0-dealii-9.6-debian-12](https://cdash.dealii.org/buildSummary.php?buildid=949) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=949) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=949) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=949) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=949) | [15804](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=949) |
| tester-voyager | [GNU-13.2.0-dealii-9.6-avx256-lts-24.04](https://cdash.dealii.org/buildSummary.php?buildid=950) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=950) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=950) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=950) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=950) | [15807](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=950) |
| tester-voyager | [GNU-13.2.0-dealii-9.6-ubuntu-24.10](https://cdash.dealii.org/buildSummary.php?buildid=951) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=951) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=951) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=951) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=951) | [15804](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=951) |
| tester-voyager | [GNU-13.2.0-dealii-9.6-ubuntu-lts-24.04](https://cdash.dealii.org/buildSummary.php?buildid=952) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=952) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=952) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=952) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=952) | [15804](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=952) |
| tester-voyager | [GNU-13.2.0-dealii-9.6-avx512-lts-24.04](https://cdash.dealii.org/buildSummary.php?buildid=953) | [4f9d76](https://cdash.dealii.org/viewUpdate.php?buildid=953) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=953) | [4](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=953) | [1](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=953) | [15806](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=953) |
| tester-voyager | [GNU-14.1.1-master-std=c++20-20240704](https://cdash.dealii.org/buildSummary.php?buildid=960) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=960) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=960) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=960) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=960) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=960) |
| tester-voyager | [GNU-13.1.1-master-standalone_kokkos-20230507](https://cdash.dealii.org/buildSummary.php?buildid=961) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=961) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=961) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=961) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=961) | [46](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=961) |
| tester-voyager | [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/buildSummary.php?buildid=962) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=962) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=962) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=962) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=962) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=962) |
| tester-voyager | [GNU-12.2.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=963) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=963) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=963) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=963) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=963) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=963) |
| tester-voyager | [GNU-11.3.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=964) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=964) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=964) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=964) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=964) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=964) |
| tester-voyager | [GNU-10.4.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=965) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=965) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=965) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=965) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=965) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=965) |
| tester-voyager | [Clang-18.1.8-master-unity_build-20240704](https://cdash.dealii.org/buildSummary.php?buildid=968) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=968) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=968) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=968) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=968) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=968) |
| tester-voyager | [Clang-18.1.8-master-std=c++20-20240704](https://cdash.dealii.org/buildSummary.php?buildid=973) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=973) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=973) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=973) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=973) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=973) |
| tester-voyager | [Clang-16.0.6-master-taskflow-20230708](https://cdash.dealii.org/buildSummary.php?buildid=974) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=974) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=974) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=974) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=974) | [50](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=974) |
| tester-voyager | [Clang-16.0.6-master-autodetection-20230507](https://cdash.dealii.org/buildSummary.php?buildid=975) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=975) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=975) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=975) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=975) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=975) |
| tester-voyager | [Clang-15.0.6-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=976) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=976) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=976) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=976) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=976) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=976) |
| tester-voyager | [Clang-14.0.6-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=977) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=977) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=977) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=977) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=977) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=977) |
| tester-voyager | [Clang-13.0.1-master-autodetection-20230116](https://cdash.dealii.org/buildSummary.php?buildid=978) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=978) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=978) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=978) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=978) | [48](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=978) |
| tester-voyager | [GNU-14.1.1-master-autodetection-20240704](https://cdash.dealii.org/buildSummary.php?buildid=979) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=979) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=979) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=979) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=979) | [16000](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=979) |
| tester-voyager | [GNU-13.1.1-master-minimal-20230116](https://cdash.dealii.org/buildSummary.php?buildid=980) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=980) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=980) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=980) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=980) | [8114](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=980) |
| tester-voyager | [GNU-13.1.1-master-64bit_indices-20230507](https://cdash.dealii.org/buildSummary.php?buildid=981) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=981) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=981) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=981) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=981) | [16244](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=981) |
| tester-voyager | [Clang-18.1.8-master-autodetection-20240704](https://cdash.dealii.org/buildSummary.php?buildid=982) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=982) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=982) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=982) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=982) | [15990](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=982) |
| tester-voyager | [Clang-16.0.6-master-sanitizer-20230622](https://cdash.dealii.org/buildSummary.php?buildid=983) | [2ff715](https://cdash.dealii.org/viewUpdate.php?buildid=983) | [0](https://cdash.dealii.org/viewBuildError.php?buildid=983) | [0](https://cdash.dealii.org/viewBuildError.php?type=1&buildid=983) | [0](https://cdash.dealii.org/viewTest.php?onlyfailed&buildid=983) | [7956](https://cdash.dealii.org/viewTest.php?onlypassed&buildid=983) |

**Comment by blaisb** [comment]
I will make a list of all the broken examples that I have identified here. I should be done with re-running all of them today:

Step 33 - #17409

**Comment by tamiko** [comment]
The following is a list of ouststanding tasks that have to happen after we tagged a release (candidate). In order to avoid duplicated efforts, add your a tag `@name` with your name after `assigned:`. Finally, tick of the box when the task is done.

 - [ ] <b>Generate the documentation on the webserver</b> (assigned:)
 - [ ] <b>Adjust `header.include` on the homepage</b> (assigned:)
   Change links to the documentation of the most recent version; change the link to the changes_after_X_Y_Z.html file.
 - [ ] <b>Adjust `news.html` on the homepage</b> (assigned:)
   * add a new entry for the release using the link to the copied changes.h file from above
   * also rotate the news entry in the short news blurbb on the fron page in `index.html`
 - [ ] <b>Generate MAC bundles and attach to current (pre-)release</b> (assigned:)
 - [ ] <b>Update deal.II package in Spack</b> (assigned:)
 - [ ] <b>Update deal.II package in Candi</b> (assigned:)
 - [ ] <b>Update deal.II package in Gentoo</b> (assigned:)
 - [ ] <b>Update deal.II package in Ubuntu/Debian and generate PPA for Ubuntu LTS</b> (assigned:)
 - [ ] <b>Update deal.II package in Archlinux AUR</b> (assigned:)
 - [ ] <b>Update deal.II Virtualbox Images</b> (assigned:)
 - [ ] <b>Release announcements</b> (assigned: &mdash;)
   * [ ] on the user mailing list
   * [ ] send a separate mail with the list of contributors for this release
   * [ ] on social media (facebook, twitter)
   * [ ] send a news item to NADigest; web form breaks longer lines automatically, so keep them long to avoid awkward formatting
   * [ ] SIAM CS&E digest
 - [ ] <b>Update wikipedia pages</b> (assigned:)
   * https://en.wikipedia.org/wiki/Deal.II
   * https://en.wikipedia.org/wiki/List_of_finite_element_software_packages

**Comment by bangerth** [comment]
What's our status for Virtualbox and Spack?

**Comment by luca-heltai** [comment]
Spack is in the review process. There are issues with vectorization in dealii for ARM neoverse V1:

https://github.com/spack/spack/pull/45554#issuecomment-2460141560

**Comment by bergbauer** [comment]
> There are issues with vectorization in dealii for ARM neoverse V1:

This is fixed on master by #17739

**Comment by luca-heltai** [comment]
Shall we make a 6.1 release with this? @tamiko ?

**Comment by bangerth** [comment]
We might also want to include #17723/#17872 into a 9.6.1.

**Comment by masterleinad** [comment]
#17874 includes all the pull requests suggested to cherry-pick above.

**Comment by drwells** [comment]
We should also consider #17894 and #17895.

**Comment by masterleinad** [comment]
#17894 fixes a feature that isn't included in the latest release (https://github.com/dealii/dealii/pull/17579).
