### ISSUE TITLE
Ideas for new tutorials

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3072]
some ideas for new tutorial programs to write (please add):
- [x] parallel Navier-Stokes solver with common benchmark problems ( #3116 )
- [x] usage of data stored in quadrature points in parallel, improve ContinuousQuadratureDataTransfer?
- [x] parallel SolutionTransfer example, maybe checkpointing/serialization
- [x] more geometric multigrid examples (@tjhei, @kronbichler, ...)
- [x] multiphysics examples

**Comment by drwells** [comment]
A 'canned' NS solver is something that a lot of people are interested in (myself included).

**Comment by tjhei** [comment]
> A 'canned' NS solver

I have a serial, stationary NS solver tutorial coming soon and a parallel, time-dependent one planned (if I ever get to cleaning it up).

**Comment by jppelteret** [comment]
I hope to be able to contribute an example in magneto-statics (vector potential / Nedelec elements; likely nonlinear) somewhere towards March next year. I’ve also been thinking about a problem in nonlinear thermo-electro-elasticity for the future.

**Comment by kronbichler** [comment]
@Rombur, @kalj and I also plan to introduce another matrix-free tutorial including an option to switch to the GPU.

There is also a plan for another matrix-free tutorial once we have the DG functionality merged.

**Comment by bangerth** [comment]
I like all of this. Now we just need to get more contributions to the code gallery!

**Comment by danshapero** [comment]
An inverse problem (e.g. tomography) might be interesting; it could even build off the existing Helmholtz solvers.

**Comment by drwells** [comment]
This goes in a completely opposite direction than the other suggestions but I think that it is on topic for this issue. I spent some time talking with John Burkhardt this weekend about his experiences in teaching a class based on deal.II. Our conclusion was that the early tutorials don't make 'easy things easy': we should offer very simple answers to questions like

1. How do I make a function?
2. How do I set up a mesh?
3. How do I pick a finite element?

With smaller examples. He mentioned that his students get overwhelmed by the giant list of `#include` files and don't see what comes from where.

I suppose what I am proposing is it might be worthwhile to have a set of tutorials that are absolutely minimal in what they do (for example, a ten line program that calls `GridGenerator` and then saves the mesh somewhere). This would help at least someone who is not a primary developer (but likes the library) teach a deal.II course. Thoughts?

**Comment by tjhei** [comment]
> early tutorials don't make 'easy things easy'

In general I think that we require too much boiler-plate to get things going. Step-1 is really short if you remove the comments.

> we should offer very simple answers to questions like

Is this just a matter of making more (smaller) steps, simplifying or is more a different kind of material? I let my students play with meshes, FEs, boundaries, constraints,etc. in form of assignments related to tutorial programs. Making assignments with solutions available might be the right thing to do here.

> it might be worthwhile to have a set of tutorials that are absolutely minimal in what they do (for example, a ten line program that calls GridGenerator and then saves the mesh somewhere).

Like step-1? Or step-49 if you want to do more?

**Comment by jppelteret** [comment]
> I suppose what I am proposing is it might be worthwhile to have a set of tutorials that are absolutely minimal in what they do (for example, a ten line program that calls GridGenerator and then saves the mesh somewhere). 

Would it be sensible to then have a "Teaching/Learning material" section for these types of mini-codes, in the same spirit as the code gallery?

**Comment by drwells** [comment]
@tjhei I did look at step 1 again, but even that uses some AMR (my point is that it is not as simple as possible, which is what John is looking for).

@jppelteret I am not sure where such little tutorials would go. Since the goal would be to make them as tiny as possible they don't really fit the style of the rest of the steps, so it might be better to have them under some other category; something like "getting started with simple examples".

**Comment by tjhei** [comment]
> @tjhei I did look at step 1 again, but even that uses some AMR (my point is that it is not as simple as possible, which is what John is looking for).

But the ``first_grid()`` function is just 7 lines of code. Do you think having a second function in the same file is the problem here?

**Comment by drwells** [comment]
@tjhei I think so in this circumstance: the impression I got was that pointing a newbie to a 10 line program that generates a mesh would be better than pointing them halfway into step-1 since the former is self contained.

**Comment by tjhei** [comment]
@drwells I am reading back over my comments above and I realize they are a bit snarky, sorry about that.

I am totally in favor of more simple examples and feedback like this is very valuable to have for us. I am still not sure how to implement these ideas, though.

**Comment by drwells** [comment]
@tjhei I took what you said as honest criticism. I was not offended :)

My conclusion from the conversation is that it would be valuable to have a dozen or so ten line examples that just provide quick answers to questions. This does duplicate what we have in the first few steps a bit so I don't know how to fit it in with what we already have.

**Comment by tjhei** [comment]
> I don't know how to fit it in with what we already have.

To expand a bit on my suggestion:

We can post questions and answers for individual tutorials. For step-1 I had the following assignments:
```
(a) Create an image of an L-shape domain (add another function to step-1).
(b) Refine the mesh in a) adaptively around the re-entrant corner 4 times.
(c) Create a helper function that takes a Triangulation and outputs the following infor-
mation: number of levels, number of cells, number of active cells. Test this with the
(now three) meshes.
(d) Output the mesh as an svg file instead of eps. Open it in a browser to display it.
(e) Create a 3d cylinder and refine it 3 times (globally). Try outputting to gnuplot format
too.
(f) Bonus: create a 3d unit cube and create a loop that in each step a) refines globally
once, b) outputs the number of active cells, c) the amount of memory in megabytes
required to store this mesh (look for a function called memory_consumption()). Do this
for 6 global refinements first. How many refinements can you fit into memory of your
computer (typing free in the terminal tells you how much memory you have)?
```
Notice that they fit your examples pretty well and only require a few lines of code each.

**Comment by bangerth** [comment]
I'm sympathetic to the idea of adding more tutorial programs, or adding other ways of providing better documentation or training -- after all, I seem to have written most of it ;-)

The question I've been pondering reading through all of this is not whether to add more, but more *where* to put things. The graph of tutorial programs is already quite dense: http://dealii.org/developer/doxygen/deal.II/Tutorial.html . If we were to split these programs even finer, I have difficulty seeing how that remains navigable. 

I do like the idea of @tjhei 's worked examples. Many of the early (and some of the later) tutorial programs already have a "Possibilities for extensions" section at the bottom that mostly grew out of similar exercises I ran in my classes, but they are more open ended. What if we just added a section "Exercises" to (some of the) tutorials, before or after the "Possibilities for extensions" that have questions in the style @tjhei showed? If we think a bit about the formatting, we can introduce doxygen macros that automatically render things nicely.

**Comment by bangerth** [comment]
I also have something way out there. I came across a new colleague here at Colorado State who sent me one of her papers: http://www.inf.unibz.it/~gbavota/papers/icse2015_muse.pdf . It's a bit of a crazy idea, but also ingenious in that they try to extract use cases for individual functions and put them into the class or function documentation. I think that's totally cool. The only downside is that their method is only available for Java right now :-( It's a good read, though, well worth the 20 or 30 minutes to get through it!

**Comment by tjhei** [comment]
> What if we just added a section "Exercises" to (some of the) tutorials

That sound great. I am a bit worried that our solutions might stop working so if we can make them compilable/testable, that would be great.

> extract use cases

I think we could link from documentation to tutorials or exercises within tutorials easily. That would be a manual approach, but still very helpful for beginners.

**Comment by bangerth** [comment]
Yes, that's a good point about staying compilable/testable. doxygen has a way to include code from some other place, referencing file line number. That's how some of the code in `examples/doxygen` got there. It allows to separately compile and test these snippets. But I'm not fond of this solution either because it requires splitting documentation into many files, and that doesn't help with maintaining either.

> I think we could link from documentation to tutorials or exercises within tutorials easily. That would be a manual approach, but still very helpful for beginners.

Yes, we already do this in many places. More places would definitely be useful. But it still only links to a whole program -- the approach in the paper is to show ten-line snippets of using a function in some context, which I think is actually quite a nice idea, but tedious to do if you want to do it manually for a large number of functions.

**Comment by tjhei** [comment]
> show ten-line snippets of using a function in some context,

Hey, I can do that too: https://github.com/dealii/dealii/search?utf8=%E2%9C%93&q=hyper_rectangle

:-)

> but tedious to do if you want to do it manually for a large number of functions.

Yes, agreed. I think putting some effort into simple things like ``GridGenerator`` might be all that is needed, at least if I understand @drwells correctly.

**Comment by drwells** [comment]
We have done most of these - I migrated the rest into a project.
