### ISSUE TITLE
8.5.0 Release

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#3893]
We would like to slowly start the process for the 8.5 release. This means that we need some help to fix current issues, do some extensive testing, and not introduce too much new and fragile stuff for now.

Things to do:
- [x] cleanup some more of the broken tests
- [x] check newest TBB and boost
- [x] check newest clang and gcc
- [x] check newest intel compiler
- [ ] update candi, advertise
- [ ] reevaluate the windows story: https://github.com/dealii/dealii/issues/1921
- [ ] document ubuntu on windows 10
- [ ] go through open issues: https://github.com/dealii/dealii/milestone/3

**Comment by bangerth** [comment]
If we can't get windows to work natively, then we're no worse off than we were before. I wouldn't consider this a show-stopper.

**Comment by drwells** [comment]
Oh happy day!

I will spend some time reviewing the changes in the new version of boost to see if we should pick up any new patches. I don't think it is necessary to update to 1.63 (though it would not be so hard to do it).

Our bundled version of TBB is pretty old. Is there interest in bundling the newest one?

**Comment by tjhei** [comment]
> If we can't get windows to work natively, then we're no worse off than we were before. I wouldn't consider this a show-stopper.

The short version is: ubuntu on windows 10 works amazingly well (including MPI!) and we have regressed on MSVC (link times with the debug library are now >10 minutes). I am not sure if the last problem is due to changes in MSVC or on our end. Not a show-stopper, but I am considering to remove "experimental support" from the readme.

**Comment by davydden** [comment]
@tjhei 

> update candi, advertise

in this case, may I suggest that we advertise `spack` as well? Different strokes for different folks. Spack works for me on mac, ubuntu and linux cluster.

> check newest TBB and boost

I see no issues compiling current master with `tbb@2017.3`, `boost@1.63.0` and Apple's `clang@8.0.0`. 
Will check the same on `ubuntu` with `gcc@6.3.0` tomorrow...

**Comment by bangerth** [comment]
> Our bundled version of TBB is pretty old. Is there interest in bundling
> the newest one?


Let's keep updating bundled packages for after a release when we have 
plenty of time to iron out any issues that may appear.

**Comment by kronbichler** [comment]
I moved a few big issues opened by me to the release 9.0 because those are big changes that are too brittle before the release. Likewise, the DG (face integral) extension of `MatrixFree` which has been on our local machines for 3 years and has matured to be almost ready will also wait until after the 8.5 release.

**Comment by tamiko** [comment]
A quick build test for gcc-6.3.0: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=4245

**Comment by tamiko** [comment]
Btw. the poor cdash instance got its quarterly sledgehammer to the head [1] - in case anyone wonders.
[1] We racked up ~40GB of test results.

**Comment by tamiko** [comment]
A quick build test for clang-3.9.1: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=4249

**Comment by bangerth** [comment]
Other than #3896, I have ~8500 tests that succeed and no noteworthy other failures.

**Comment by koecher** [comment]
>  update candi, advertise

@tjhei I'll open a request for that.

**Comment by davydden** [comment]
apart from a few already known issues, `dealii` build by Spack with `clang` and all the latest versions of packages pass the test suite on macOS Sierra. Detailed versions of important dependencies are:
```
dealii@develop%clang@8.0.0-apple+arpack+doc+gsl+hdf5~int64+metis+mpi+netcdf+oce+p4est+petsc+python+slepc+trilinos arch=darwin-sierra-x86_64
    ^arpack-ng@3.4.0%clang@8.0.0-apple+mpi+shared arch=darwin-sierra-x86_64
        ^openblas@0.2.19%clang@8.0.0-apple~openmp+pic+shared arch=darwin-sierra-x86_64
        ^openmpi@2.0.2%clang@8.0.0-apple~java~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt arch=darwin-sierra-x86_64
    ^boost@1.63.0%clang@8.0.0-apple+atomic+chrono+date_time~debug+filesystem~graph~icu+iostreams+locale+log+math+mpi+multithreaded+program_options+python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer+wave arch=darwin-sierra-x86_64
    ^gsl@2.3%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^hdf5@1.10.0-patch1%clang@8.0.0-apple+cxx~debug+fortran+mpi+pic+shared~szip~threadsafe arch=darwin-sierra-x86_64
    ^metis@5.1.0%clang@8.0.0-apple~debug~gdb~int64~real64+shared arch=darwin-sierra-x86_64
    ^muparser@2.2.5%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^netcdf@4.4.1.1%clang@8.0.0-apple~cdmremote~dap~hdf4 maxdims=1024  maxvars=8192 +mpi~parallel-netcdf+shared arch=darwin-sierra-x86_64
    ^netcdf-cxx@4.2%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^oce@0.18%clang@8.0.0-apple+tbb arch=darwin-sierra-x86_64
        ^tbb@2017.3%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^p4est@2.0%clang@8.0.0-apple arch=darwin-sierra-x86_64
    ^petsc@3.7.5%clang@8.0.0-apple+boost~complex~debug+double+hdf5+hypre~int64+metis+mpi+mumps+shared+superlu-dist arch=darwin-sierra-x86_64
        ^hypre@2.11.1%clang@8.0.0-apple~int64~internal-superlu~shared arch=darwin-sierra-x86_64
        ^mumps@5.0.2%clang@8.0.0-apple+complex+double+float~int64~metis+mpi~parmetis~ptscotch~scotch+shared arch=darwin-sierra-x86_64
            ^netlib-scalapack@2.0.2%clang@8.0.0-apple~fpic+shared arch=darwin-sierra-x86_64
        ^parmetis@4.0.3%clang@8.0.0-apple~debug~gdb+shared arch=darwin-sierra-x86_64
        ^superlu-dist@5.1.1%clang@8.0.0-apple~int64 arch=darwin-sierra-x86_64
    ^slepc@3.7.3%clang@8.0.0-apple+arpack arch=darwin-sierra-x86_64
    ^suite-sparse@4.5.3%clang@8.0.0-apple+fpic+tbb arch=darwin-sierra-x86_64
    ^trilinos@12.10.1%clang@8.0.0-apple+boost~debug+hdf5+hypre+metis+mumps~python+shared+suite-sparse~superlu+superlu-dist~xsdkflags arch=darwin-sierra-x86_64
```

**Comment by tjhei** [comment]
I can report the intel 2017 17.0.1 works.

**Comment by davydden** [comment]
apart from https://github.com/dealii/dealii/issues/3958 and https://github.com/dealii/dealii/issues/3915 , `dealii` build by Spack with `gcc@6.3.0` and all the latest versions of packages (same as [above](https://github.com/dealii/dealii/issues/3893#issuecomment-278245587) ) pass the test suite on Ubuntu 16.04 .

**Comment by tjhei** [comment]
> in this case, may I suggest that we advertise spack as well? Different strokes for different folks. Spack works for me on mac, ubuntu and linux cluster.

I updated the download page to mention candi, spack, and homebrew. I also reorganized things. How does it look? (https://www.dealii.org/download.html might take a bit to update)

@tamiko I also put the debian blurb back in. Is this okay?

**Comment by davydden** [comment]
> How does it look?

looks fine. I few suggestions:

(i) please fix the URL to spack https://spack.io 
(ii) add Homebrew URL http://brew.sh 

(iii)  let's use official description for Spack (from the link above): 

> is a package manager for supercomputers, Linux, and macOS. With Spack, you can build a package with multiple versions, configurations, platforms, and compilers, and all of these builds can coexist on the same machine.

(rephrase the second sentence to your taste, if needed). This nicely complements candi's selling point 

> compile many dependencies for deal.II with minimal effort.

**Comment by tjhei** [comment]
okay, fixed.

**Comment by tamiko** [comment]
> @tamiko I also put the debian blurb back in. Is this okay?

Look good!

What about we also mention Ubuntu (and mention Yakkety Yak and Zesty
Zapus) [1]?

Best,
Matthias

[1] https://launchpad.net/ubuntu/+source/deal.ii

**Comment by davydden** [comment]
@tjhei on the download page http://www.dealii.org/download.html there is "Take the user survey", which is already finished, right? I guess the button and link should be removed.

**Comment by tjhei** [comment]
> @tjhei on the download page http://www.dealii.org/download.html there is "Take the user survey", which is already finished, right? I guess the button and link should be removed.

I think so, but I think @bangerth left it there on purpose. @bangerth are you okay with me removing it?

**Comment by tjhei** [comment]
> What about we also mention Ubuntu (and mention Yakkety Yak and Zesty
> Zapus) [1]?

done.

**Comment by kronbichler** [comment]
I did test various configurations of external libraries on my machine (see the various submissions to the experimental track from the `maxwell` machine on cdash), starting from MPI with neither Trilinos nor p4est, MPI+p4est, MPI+p4est+Trilinos+PETSc, both with standard compiler flags and with `-march=native` which enables FMA and they all are passing with the usual 4-28 test failures, with 14 failures due to FMA in release mode and also the rest is uncritical.

I also ran with the developer version of gcc-7 and everything apart from boost and a bunch of warnings which me might or might not look into appears fine. For boost, I would need to force the bundled boost because the system boost conflicts due to the C++11 abi.

**Comment by bangerth** [comment]
> @tjhei <https://github.com/tjhei> on the download page
> http://www.dealii.org/download.html there is "Take the user survey", which is
> already finished, right? I guess the button and link should be removed.

I had kept it there for a while longer and we kept getting a couple of 
responses every week. But you're right, it's time to kill it. I removed the link.

**Comment by davydden** [comment]
@tjhei my builds have

> newest TBB and boost

and i don't see any extra failing tests. So i think you can mark this as done.

**Comment by davydden** [comment]
I also submitted my tests via CDash (experimental track, name `davyddenubuntu` and ‘MBP-Denis’), namely : standard build, 64bit indices, complex-valued PETSc/SLEPc, etc. Some of those got removed, as far as I can tell. Bottom line: no extra failing tests.

**Comment by Rombur** [comment]
I checked the python tests on ubuntu and they work.

**Comment by kronbichler** [comment]
I worked hard during the last few days to get the test failures down to the level where I understand all test failures on my machines with various variants, going from MPI to no-MPI, noC++11, and no-threads. (And fixed a few bugs in the library as well.) I think we can tick the "fix some of the failing tests" now...

**Comment by bangerth** [comment]
Thanks, @kronbichler , and everyone else who helped with this. Your efforts are appreciated!

**Comment by luca-heltai** [comment]
@davydden , since you have a working spack configuration with Mac, would you mind creating a package with it? 

Instructions for 8.5:

`export BASE=/Applications/deal.II-8.5-spack.app/Contents/Resources/`

- [ ] mkdir -p $BASE and clone spack there (`$BASE/opt/spack`).
- [ ] configure it to throw all its files and libraries somewhere under `$BASE/opt/spack`
- [ ] build everything deal.II depends on, *except* deal.II itself
- [ ] put your deal.II source directory tree there as well (say `$BASE/opt/dealii-src`), without the .git subdirectory
- [ ] outside the $BASE dir, build the package with the command

```
cmake \
-GNinja \
-DDEAL_II_CPACK_EXTERNAL_LIBS:PATH=spack \
-DCMAKE_INSTALL_PREFIX:PATH=$BASE \
-DDEAL_II_COMPONENT_PACKAGE:BOOL=ON \
-DDEAL_II_CPACK_BUNDLE_NAME:STRING=deal.II-8.5-spack \
/path/to/your/dealii/src-directory/

ninja package
```
- [ ] 

This will create a dmg containing a copy of your `/Applications/deal.II-8.5-spack.app` directory, including a working spack configuration, and dealii source tree.

If you do that, then Timo should be able to sign the package by downloading the package, and repeating only the last step (the build of the package itself, while setting -DCPACK_BUNDLE_APPLE_CERT_APP=...)

**Comment by davydden** [comment]
@luca-heltai i think it would be more complicated to ship the App with Spack because everything is build with RPATH's.

> or sharing with me your configuration files, so that I can do one myself

those are very standard (see link below). Generally i just build GCC with Spack, add `gfortran` to Clang compiler in Spack (see http://spack.readthedocs.io/en/latest/getting_started.html#mixed-toolchains) and build deal.II with clang+gfortran.
[spack_config_sierra.zip](https://github.com/dealii/dealii/files/853102/spack_config_sierra.zip)

**Comment by davydden** [comment]
@luca-heltai actually, it should work fine as long as everything is done in App folder. I will give it a try...

**Comment by luca-heltai** [comment]
That's great! Thanks!

**Comment by luca-heltai** [comment]
I'll update the brew package, so that users can choose.

**Comment by davydden** [comment]
@luca-heltai i had some problems packaging, i sent you archived `deal.II-8.5-spack.app` which has everything installed and ready. I think ideally packaging for macOS should be done as a post-installation step of the Spack, not as a step during installation of deal.II. Namely, when you open the `app`, it loads terminal and have paths to Spack and installed DEAL_II_DIR set. Then, users would either work with already installed deal.II, or may additionally add extra variants, or do `git pull` for Spack and get new versions of trilinos etc, all installed in the same `app`. But, i don't know the macOS tools which do the packaging and unfortunately i don't have time to dig into it now. If you want to play around with it -- go ahead, otherwise a single brew `app` is fine.

**Comment by tamiko** [comment]
@kronbichler, @bangerth 

My userland with clang-4.0.0 and relatively up to date libraries looks fine now as well [1]. (Apart from the miscompilation issue @kronichler and @masterleinad spotted). I will give an optimized version as well as gcc-6.3.0 a run as well.

[1] http://cdash.kyomu.43-1.org/buildSummary.php?buildid=6024

**Comment by tamiko** [comment]
I suggest we aim for branching and tagging a release candidate by the end of this week (March 24) to be in line for a very early April release :-)

**Comment by luca-heltai** [comment]
As for the download page, maybe it's worth mentioning the docker images at docker hub:

https://hub.docker.com/r/dealii/dealii/tags/

these are fully functional and used in several projects now...

**Comment by bangerth** [comment]
@luca-heltai -- Do you have access to the website repo? If yes, feel free to add a blurb yourself.

**Comment by tamiko** [comment]
@Rombur @bangerth What is the status of cuda support? Shall we disable it for the current release?

**Comment by bangerth** [comment]
I have no idea :-)

**Comment by tamiko** [comment]
I would feel better to disable the configure option for the 8.5.0 release and let it mature a little bit more.

@kalj *ping*

**Comment by kalj** [comment]
@tamiko That is definitely the right thing to do for now. I plan to put some effort into this once I've submitted my thesis by the end of April. :)

**Comment by tjhei** [comment]
> @Rombur @bangerth What is the status of cuda support? Shall we disable it for the current release?

Configuration is already disabled by default or am I misunderstanding what you are proposing?

**Comment by tamiko** [comment]
@tjhei I want to completely remove the configuration option.

**Comment by tjhei** [comment]
> @tjhei I want to completely remove the configuration option.

What is the reasoning for this? It won't do any harm as is, right?

**Comment by Rombur** [comment]
@tamiko cuda is definitely not ready so this can be removed/disabled if you want to.

**Comment by tamiko** [comment]
> @tamiko cuda is definitely not ready so this can be removed/disabled if you want to.

Will do.

**Comment by masterleinad** [comment]
I just checked that a recent TBB library and a recent boost library work fine.

**Comment by tjhei** [comment]
I am now running all tutorial problems and I will tag ``-rc1`` tomorrow (hopefully with the other PRs merged)

**Comment by tjhei** [comment]
please test: https://github.com/dealii/dealii/releases/tag/v8.5.0-rc1

**Comment by tamiko** [comment]
@tjhei I changed simserv to the release branch.

**Comment by bangerth** [comment]
The RC works for me.

**Comment by drwells** [comment]
I symbolic linked in the testsuite and was able to run it with one insignificant failure (`mesh_3d_12` is off by the last digit in one line) and a timeout with `grid_tools_local_to_global_vertex_id.mpirun=2.debug`, which has failed intermittently for me for a long time.

**Comment by kronbichler** [comment]
I tested with a variety of Linux configurations (`maxwell` and `node27` results on the cdash page) and everything seems sane. There are some (expected) failures with `-Ofast` compilation but that is OK.

I even ran `ctest -R "matrix_free|mf|vector"` on Intel KNL with AVX-512, i.e., the tests that actually use 512 bit vectors, and every is passing or only differs due to roundoff. (I cannot run the whole test suite or even submit; admins won't like the former and the latter is forbidden by a firewall.)

**Comment by drwells** [comment]
I reran the test suite in C++03 mode with recent releases of packages (boost 1.63, intel-tbb 2017, etc). The following tests failed for nontrivial reasons (more than just a single digit):

```
        1471 - base/tensor_09.debug (Failed)
        1472 - base/tensor_09.release (Failed)
        6797 - opencascade/arclength_boundary_02.debug (Failed)
        6798 - opencascade/arclength_boundary_02.release (Failed)
        6833 - opencascade/plane_intersection_01.debug (Failed)
        6834 - opencascade/plane_intersection_01.release (Failed)
```

One PARPACK test template has a `>>` in it: I'll submit a PR for 8.5 to fix that.

`tensor_09` fails to compile (I think this is a GCC bug). The OC tests are OK (see #3915).

**Comment by tamiko** [comment]
With #4148 merged we should support the full range of CMake versions from 2.8.8 to 3.8.0-rc4. I checked configuring with 2.8.8, 3.7.2 and 3.8.0-rc4.

**Comment by tamiko** [comment]
gcc 4.7.4 looks good: http://cdash.kyomu.43-1.org/buildSummary.php?buildid=6272

**Comment by drwells** [comment]
@tamiko I can rebuild on arch :) what exactly do you want done? Just build everything with the most recent packages and submit results to cdash?

**Comment by tamiko** [comment]
> @tamiko I can rebuild on arch :) what exactly do you want done? Just
> build everything with the most recent packages and submit results to
> cdash?

Yes, just a build test submitted to cdash.

For Arch I was too lazy to install the dependencies by hand.

**Comment by drwells** [comment]
I built the latest relevant AUR packages and submitted the result: things look good.

**Comment by ChuckDaniels87** [comment]
I've managed to build RC1 from AUR package. I tried to submit build test to cdash but there were many missing dependencies.

**Comment by drwells** [comment]
@ChuckDaniels87 Our CMake scripts don't know about packages in the `/opt/` directory (we should probably fix this), so I ran the following script for the build tests:

```bash
#!/bin/bash
# on branch dealii-8.5
mkdir build-test
cd build-test
ctest -DDEAL_II_WITH_TRILINOS=ON -DTRILINOS_DIR=/opt/trilinos/              \
      -DDEAL_II_WITH_SLEPC=ON -DSLEPC_DIR=/opt/slepc/linux-c-opt/           \
      -DDEAL_II_WITH_PETSC=ON -DPETSC_DIR=/opt/petsc/linux-c-opt/           \
      -DDEAL_II_WITH_P4EST=ON -DP4EST_DIR=/home/drwells/Applications/p4est/ \
      -DDEAL_II_COMPONENT_DOCUMENTATION=ON                                  \
      -DDEAL_II_COMPONENT_EXAMPLES=ON                                       \
      -DDEAL_II_COMPONENT_PYTHON_BINDINGS=ON                                \
      -DDEAL_II_DOXYGEN_USE_MATHJAX=ON                                      \
      -DDEAL_II_WITH_64BIT_INDICES=ON                                       \
      -DDEAL_II_WITH_ARPACK=ON                                              \
      -DDEAL_II_WITH_BZIP2=ON                                               \
      -DDEAL_II_WITH_CXX11=ON                                               \
      -DDEAL_II_WITH_CXX14=ON                                               \
      -DDEAL_II_WITH_GSL=ON                                                 \
      -DDEAL_II_WITH_HDF5=ON                                                \
      -DDEAL_II_WITH_LAPACK=ON                                              \
      -DDEAL_II_WITH_METIS=ON                                               \
      -DDEAL_II_WITH_MUPARSER=ON                                            \
      -DDEAL_II_WITH_MPI=ON                                                 \
      -DDEAL_II_WITH_NETCDF=ON                                              \
      -DDEAL_II_WITH_OPENCASCADE=ON                                         \
      -DDEAL_II_OPENCASCADE_DIR=/opt/opencascade7/                          \
      -DDEAL_II_WITH_THREADS=ON                                             \
      -DDEAL_II_WITH_UMFPACK=ON                                             \
      -DDEAL_II_WITH_ZLIB=ON                                                \
      -j4 -S ../tests/run_buildtest.cmake
```

I added hypre and 64 bit indices to PETSc by modifying the AUR package:
```bash
echo ${CONFOPTS}
    python2 ./configure \
    --prefix=${_install_dir} \
    --PETSC_ARCH=${petsc_arch} \
    --with-64-bit-indices \
    --download-hypre=1 \
    ${CONFOPTS}
```

I installed `p4est` version 2 manually but every other package I got from either the default repositories or the AUR.

Does doing this fix your issue, or are you still missing something?

**Comment by drwells** [comment]
I also had to install `netcdf-cxx-legacy` from the AUR.

**Comment by ChuckDaniels87** [comment]
Path of opencascade is `/opt/opencascade` for me. In any case, `trilinos` package is failing to build in my system so I cannot run the full test, sorry.

**Comment by bangerth** [comment]
So what is missing? Can we cut the release?

**Comment by jppelteret** [comment]
@bangerth I'd like to add #4145 and #4174 if you don't mind.

**Comment by bangerth** [comment]
OK, both are now merged.

**Comment by jppelteret** [comment]
Thanks a lot!

**Comment by drwells** [comment]
@ChuckDaniels I don't recall having any recent problems with Trilinos (either a version installed through the AUR or compiled and installed as a local user). In the past I had to disable the python bindings but that doesn't seem to be an issue any more. If you can't figure things out then email me (wellsd2 at rpi dot edu) and I will try and help :)

**Comment by ChuckDaniels87** [comment]
@drwells I've reported a missing dependency (`gtest` package) on Trilinos AUR package. Thanks for your interest.

**Comment by tjhei** [comment]
> So what is missing? Can we cut the release?

We are getting close! I can tag, sign, and upload tomorrow for example. Right now I am looking at #4151

**Comment by tjhei** [comment]
Any last comments before I push the button? Any news on #4162?

**Comment by bangerth** [comment]
Let's just do it. There needs to be a point where we say it's good enough. I think we're at that point.

**Comment by tjhei** [comment]
and there it is: https://github.com/dealii/dealii/releases/tag/v8.5.0

If you are involved with the release paper and/or the announcement, please take a final look at /8.5/paper.tex /8.5/announcement /8.5/announcement-short

**Comment by bangerth** [comment]
I've updated the website (but not put an entry into the news). While there, I noticed that the documentation for the 8.5 has been generated without the code gallery: http://dealii.org/8.5.0/doxygen/deal.II/Tutorial.html . Is this (i) how we want it, (ii) something we want to fix, or (iii) something we may want to fix for the next release?

For reference, the dev documentation includes the code gallery: http://dealii.org/developer/doxygen/deal.II/Tutorial.html

**Comment by drwells** [comment]
After discussions with other Arch users I have taken over the AUR deal.II package (that is, the unofficial build instructions) and I also wrote an AUR package for p4est. Do we have somewhere to advertise things like this?

**Comment by davydden** [comment]
@drwells on the download page https://www.dealii.org/download.html , i guess.

**Comment by tjhei** [comment]
> I've updated the website

Thanks. I was waiting with that for the documentation to come online.

> I noticed that the documentation for the 8.5 has been generated without the code gallery

I think this is acceptable for now (it only requires one extra click). Note that this is the same for the offline-doc tarball.

I prefer to only have the code gallery online once, otherwise we have different versions of it frozen in time.

**Comment by bangerth** [comment]
On 04/07/2017 09:22 AM, Timo Heister wrote:
> I prefer to only have the code gallery online once, otherwise we
> have different versions of it frozen in time.

But that's the same as for the tutorials. It has the downside that it
makes it unnecessarily complicated for people to discover the code
gallery. For example, I can't link to it from under the 8.5 tab.

**Comment by tjhei** [comment]
> But that's the same as for the tutorials.

Sure, but we actually test the tutorials for a specific release and they are part of each release. If you include the code gallery in the 8.5.0 documentation, you are in a way creating "releases" of the code gallery in sync with each deal.II release. I am not convinced this is a good idea. I understand that this makes discovery more difficult.

**Comment by drwells** [comment]
@davydden That is the right spot to mention this.

@tamiko What is the correct way to add this to the web site?

**Comment by tjhei** [comment]
> What is the correct way to add this to the web site?

you can send me the blurb or post it here and I will put it in.

**Comment by drwells** [comment]
A question: Is anyone opposed to uploading the current set of offline documentation pictures to our relase page on GitHub? This would be a lot nicer for the type of build script Arch Linux likes. A tar ball containing all such images is about 130 MB.

**Comment by tamiko** [comment]
On Sat, Apr 15, 2017, at 15:09 CDT, David Wells <notifications@github.com> wrote:

> A question: Is anyone opposed to uploading the current set of offline
> documentation pictures to our relase page on GitHub? This would be a
> lot nicer for the type of build script Arch Linux likes. A tar ball
> containing all such images is about 130 MB.

The offline documentation tar ball contains said images. You can simply
extract them by something equivalent to (from the gentoo ebuild):


112 src_install() {                                                                  
113     if use doc && [[ ${PV} != *9999* ]]; then                                    
114         # copy missing images to the build directory:                            
115         cp -r "${WORKDIR}"/doc/doxygen/deal.II/images \                          
116             "${BUILD_DIR}"/doc/doxygen/deal.II || die                            
117         # replace links:                                                         
118         sed -i \                                                                 
119             's#"http://www.dealii.org/images/steps/developer/\(step-.*\)"#"images/\1"#g' \
120             "${BUILD_DIR}"/doc/doxygen/deal.II/step_*.html || die "sed failed"   
121     fi                                                                           

126 }

**Comment by drwells** [comment]
That should work for what I would like to do.

**Comment by tjhei** [comment]
You can also look at https://github.com/dealii/dealii/blob/master/contrib/utilities/makeofflinedoc.sh

**Comment by drwells** [comment]
@tjhei I finished the AUR package. Here is the HTML blurb:


```html
<tr>
  <td>
    <p>
      <b>Arch Linux</b>
    </p>
  </td>
  <td>
    deal.II is available in the AUR: the snapshot file is
    available for download
    <a href="https://aur.archlinux.org/packages/deal-ii/">
      here</a>.
  </td>
</tr>
```

**Comment by tamiko** [comment]
Closing :-)

**Comment by drwells** [comment]
It looks like the AUR bit is not on the web page yet. Who should I bug about this?

**Comment by tamiko** [comment]
> It looks like the AUR bit is not on the web page yet. Who should I bug about this?

Ah, you don't have commit access to the legendary SVN? :-D

We'll have to fix that. In the meantime what text would you like to have
on the webpage?

**Comment by drwells** [comment]
I don't think that I do. IIRC when I was promoted we decided to just switch the paper repository to GitHub instead of adding me there.

The text is the bit of HTML I have three messages up :)
