### ISSUE TITLE
Reproducibly failing tests

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#3911]
The following 5 tests fail on all machines:
 - [x] fe/fe_project_2d.debug (see #3896)   
 - [x] fe/fe_project_2d.release                                                       
 - [x] fe/get_fe_by_name_01.debug                                                     
 - [x] multigrid/step-16-50-mpi-linear-operator.mpirun=3.debug (see #3846, #3890)
 - [x] multigrid/step-16-50-mpi-linear-operator.mpirun=3.release
 - [x] lac/schur_complement_05.mpirun=1.debug (see #3913)
 - [x] lac/schur_complement_05.mpirun=1.release
 - [x] lac/schur_complement_05.mpirun=3.debug
 - [x] lac/schur_complement_05.mpirun=3.release

**Comment by tamiko** [comment]
Blocks #3893

**Comment by davydden** [comment]
you can add opencascade tests here https://github.com/dealii/dealii/issues/3915, to my knowledge that would be everything in the current state.

**Comment by davydden** [comment]
@tamiko i check-boxed schur_compliment tests as they should be fixed now.

**Comment by davydden** [comment]
closing this since all reproducibly failing tests now reproducibly run ok :smile:
