### ISSUE TITLE
Timers are weirdly broken

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4867]
I noticed this a few weeks ago but haven't had time to take a closer look. I ran some code with timing output that had really bizarre results so I created a smaller working example:

```cpp
#include <deal.II/base/timer.h>

#include <chrono>
#include <thread>

int main()
{
  using namespace dealii;

  TimerOutput timer(std::cout,
                    TimerOutput::OutputFrequency::summary,
                    TimerOutput::wall_times);
  timer.enable_output();

  TimerOutput::Scope scope(timer, "2");
  std::this_thread::sleep_for(std::chrono::seconds(2));
}
```

produces the following output:
```
[wellsd2@rtg1 timer-test]$ make && time make run
[ 50%] Building CXX object CMakeFiles/timer.dir/timer.cc.o
[100%] Linking CXX executable timer
[100%] Built target timer
[ 66%] Built target timer
[100%] Run timer with Debug configuraytion


+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |         2s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| 2                               |         1 |         4s |     2e+02% |
+---------------------------------+-----------+------------+------------+

[100%] Built target run
make run  0.24s user 0.05s system 12% cpu 2.290 total
```

Similarly, here is some output from step 56:
```
+---------------------------------------------+------------+------------+
| Total wallclock time elapsed since start    |      84.9s |            |
|                                             |            |            |
| Section                         | no. calls |  wall time | % of total |
+---------------------------------+-----------+------------+------------+
| (Multigrid specific)            |         3 |      31.2s |        37% |
| Assemble                        |         1 |      29.1s |        34% |
| Assemble Multigrid              |         1 |      26.8s |        32% |
| Setup                           |         1 |      4.55s |       5.4% |
| Setup - Multigrid               |         1 |      3.03s |       3.6% |
| Solve                           |         1 |       103s |   1.2e+02% |
| Solve - FGMRES                  |         1 |       101s |   1.2e+02% |
| Solve - Set-up Preconditioner   |         1 |      1.41s |       1.7% |
+---------------------------------+-----------+------------+------------+
```

which is even stranger.

Update: Here is the tracker of things to improve here:
- [x] fix the double wall time bug (see #4868)
- [x] convert things to use `std::chrono` instead of `gettimeofday`
- [x] clean up the documentation and variable names a bit
- [x] clean up the MPI vs. non-MPI versions: we can use our own MPI stubs instead of `#ifdef`s in `timer.h` and `timer.cc`

Update 2: a few more follow-up tasks
- [x] Check that things work correctly on Windows (see #4927)
- [x] ~~Use `boost::optional` to store uninitialized `MinMaxAvg` values~~ Update: this won't work in the case that a user stores the returned reference and then reads it again later. Since there is no way to do this in a backwards-compatible way lets skip it for now.
- [x] Update documentation of `sync_wall_time` (we now, as of #4549 use it to sync CPU times too)
- [x] Review general class documentation
- [x] Review how we use the class in the tutorial programs
- [x] Review name choices again (if we rename things added in #4549 then we can just remove the older version)

**Comment by drwells** [comment]
We can probably clean up the timer code a lot with C++11 timing features.

**Comment by drwells** [comment]
It looks like we rely on Unix or Windows-specific time-measuring functionality. We should get rid of the functionality guarded by `DEAL_II_HAVE_SYS_TIME_H` and `DEAL_II_HAVE_SYS_RESOURCE_H` (and equivalent windows stuff) in favor of things in `std::chrono`.

**Comment by tamiko** [comment]
@drwells I cannot agree more. I would really like to see more of the POSIX stuff removed (from our codebase and the cmake configure).

**Comment by drwells** [comment]
I am working on this now. We can make things a lot prettier by using `std::chrono::duration` instead of `double` for storing durations and `std::chrono::system_clock::now()` instead of `gettimeofday()`.

I am still baffled by these strange percentage calculations.

**Comment by drwells** [comment]
I am going to focus on this for the next few days: I don't like having open pull requests but this is a serious problem.

**Comment by bangerth** [comment]
Using the C++11 features is clearly the way to go but I am surprised by the output you show. We've been using this class up and down in ASPECT, and I can't recall seeing anything like this before. Do you have an idea why it gets the numbers so wrong?

**Comment by drwells** [comment]
Yes. Patch incoming.

**Comment by drwells** [comment]
@bangerth I looked, earlier, at some ASPECT timing results (e.g., geodynamics/aspect#1565) and I noted that the percentages added up to more than 100 (in this case 148). However, the commit that double counted the wall time was in June, and geodynamics/aspect#1565 was in May; I suspect that there are more bugs lurking in this class.

**Comment by bangerth** [comment]
Ah, that makes sense. We've been using this class for years and it worked well. It makes sense that we may not have seen this in just the last couple of months.

**Comment by gassmoeller** [comment]
Do not use the ASPECT timings as a guideline for bugs in that class. We have nested timing section (e.g. many of the Particle sections are part of the postprocessing). I am not saying there  is no bug (I dont know), but that the ASPECT timings do not add up is expected.

**Comment by davydden** [comment]
In my code I don't have nested section but I see the bug roughly for a month or so.

**Comment by drwells** [comment]
@gassmoeller This is a good point.

**Comment by kronbichler** [comment]
> We can make things a lot prettier by using `std::chrono::duration` instead of `double` for storing durations and `std::chrono::system_clock::now()` instead of `gettimeofday()`.

While here, shouldn't we use `std::chrono::high_resolution_clock` for the wall time? On my system, the latter has precision down to the nanosecond range - not sure about the accuracy in that range or overhead, though, it seems it still does a system call to `clock_gettime`.

**Comment by drwells** [comment]
If I recall correctly (the original author of the library discusses this in https://www.youtube.com/watch?v=P32hvk8b13M) `high_resolution_clock` is, in practice, always a `typedef` for `system_clock` or `steady_clock`. My tentative branch uses `system_clock`, which does have nanosecond resolution. My current branch does something like

```cpp
  // from timer.h

  /**
   * typedef for the type of clock used by this class.
   */
  typedef std::chrono::system_clock clock_type;

  /**
   * typedef for the time point type of the clock.
   */
  typedef clock_type::time_point time_point_type;

  /**
   * typedef for the duration type of the clock.
   */
  typedef clock_type::duration duration_type;

  // ...

  time_point_type current_lap_starting_wall_time;

  // ...
  duration_type accumulated_wall_time;
```

and

```cpp
  // from timer.cc
  rusage usage;
  getrusage (RUSAGE_SELF, &usage);
  const double dtime = usage.ru_utime.tv_sec + 1.e-6 * usage.ru_utime.tv_usec;
  last_lap_cpu_time = dtime - initial_cpu_time;
  last_lap_time = clock_type::now() - current_lap_starting_wall_time;
```

one place where `chrono` really shines is that it makes it clear which types are time points and which are durations: this makes the code a lot easier to understand (and we can just convert the output back to double with an auxilary function).

**Comment by bangerth** [comment]
Yes, `chrono` is nicely designed in that it represents things of different semantics with different data types :-)

**Comment by kronbichler** [comment]
I agree that `high_resolution_clock` is most often one of those other two timers. You seem to have looked more closely at those data types than I have - if I had to choose between `system_clock` and `steady_clock`, I would pick the latter: cppreference [1] says it "is most suitable for measuring intervals". Is there anything I'm missing?

[1] http://en.cppreference.com/w/cpp/chrono/steady_clock

**Comment by kronbichler** [comment]
I had a short look at the overhead of those timers: At least on my machine, all of `steady_clock`, `system_clock` and `high_resolution_clock` are around `2.7e-8` seconds or 80 clock cycles (Linux 64 bit).

**Comment by drwells** [comment]
I initially went with `system_clock` only because I think that we are currently using it through `gettimeofday`: `steady_clock` is a better choice for our needs.
