### ISSUE TITLE
Boundary deprecation meta-tracker

### ISSUE THREAD

**Issue by drwells** [dealii/dealii#4921]
We have a lot of open boundary-related PRs and issues; lets collect them in one place. I'll put additional TODOs here instead of opening new issues.

Work to do so far:
- [x] Remove boundary usage internally (see #4798)
- [x] Formally deprecate all of the boundary classes (see #4799) (see #5222)
- [x] Update documentation (see #4800)
- [x] Convert all test cases still using `Boundary` to use the respective `Manifold` classes.
- [x] Correctly implement `GridTools::project_to_object`, a free function replacing `Boundary::project_to_surface` (part of #4798)
- [x] Reimplement missing boundary classes (e.g., `ConeBoundary` and the various OpenCASCADE boundary classes) as Manifolds

Since we were still merging patches for Boundary classes (e.g., #4447) until recently I would prefer to move very conservatively here and not outright remove the boundary classes. #4799 still permits (modulo fixing the successor to `project_to_surface`) attaching boundaries and using them in the standard way. I would prefer that we keep the only break small (where we use `project_to_object` which in turn uses `get_new_point`, instead of the possibly user-provided `project_to_surface` see #4798).

**Comment by drwells** [comment]
This definitely needs to go in 9.0. I suspect that I can finish updating the tutorial programs this week.

**Comment by drwells** [comment]
AFAIK all of the boundary stuff is now gone, so this can be closed :tada:
