### ISSUE TITLE
Generalized Support points tracker

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4992]
This is a short TODO list of what I plan to implement over the next days.

class FESystem
 - [x] Populate `generalized_support_points` (see #4993)
 - [x] Fix `convert_generalized_support_point_values_to_dof_values` (see #4999)

`VectorTools::interpolate`
 - [x] Refactor to use `get_generalized_support_points` and `convert_generalized_support_point_values_to_dof_values` (see #4857)
 - [x] get the transformation right™

 - [ ] parallelize `VectorTools::interpolate`
 - [ ] unify code with `interpolate_based_on_material_id`
 - [ ] support transformation of systems.
 
Fix up finite elements
 - [ ] Make sure interpolation matrices are constructed correctly (especially for Nédélec and Raviart-Thomas).
 - [ ] Make `FE_Nedelec` happy (see #5012)

`DoFTools`/`FETools`
 - [ ] make `FETools::convert_generalized_support_point_values_to_dof_values` reentrant.
 - [ ] have a look at corresponding functions there.

Fix tests
 - [ ] bits/step-15
 - [ ] dofs/interpolate_q_system_mixed_01

Also:
 - [ ] update the glossary entry

**Comment by tamiko** [comment]
Discuss:
 - [ ] Should we try to deprecate `get_unit_support_points`?

**Comment by tamiko** [comment]
Updates will come in smaller, self-contained PRs.

**Comment by bangerth** [comment]
In the list above, you switch between "representative point" and "support point". Since the latter term is already used, should we just stick with it?

**Comment by bangerth** [comment]
Why does this issue close #328?

**Comment by tamiko** [comment]
@bangerth 
> Why does this issue close #328?

Because it is now a bullet point in the list ;-)

**Comment by tamiko** [comment]
@bangerth @luca-heltai 

I have a bit of a problem with our current interfaces.

In essence `convert_generalized_support_points_to_dof_values` has a design flaw - in essence it requires vectors with `double` type. But this clashes with `VectorTools::interpolate` that is essentially templated in `VECTOR::value_type`.

The only real solution I see is to rewrite `convert_generalized_support_points_to_dof_values` to return a reference to a transfer matrix.

The other options aren't particularly stellar as well:
 - add a template to `convert_generalized_support_points` doesn't work, the function is (at it should be) virtual.
 - working around the call with hundreds of lines of code using intermediate storage in `VectorTools::interpolate` is incredibly ugly (and even more annoying for `std::complex`).
 - only instantiating for real & double vector types is also not stellar.

**Comment by bangerth** [comment]
Yes, I think returning the matrix makes sense. It is, after all, a linear operation to convert from (generalized) support points to DoF values, so it needs to be possible to represent things as a matrix. (One could return a `linear_operator`, but its natural representation would simply be to store the elements of a full matrix.)

Returning a full matrix representation has the advantage that you can just call the function once at the beginning of `VectorTools::interpolate()`, instead of once on each cell. (I am not 100% sure that all elements should return the same matrix on every cell; but, at least at the moment, they all do because they only work on the reference cell.)

**Comment by luca-heltai** [comment]
I think this is related to the type that is stored in the `FiniteElement`. We only store doubles there, and I see no way to transform this information to a different type. 

Another possibility would be to add a
~~~
FullMatrix<NumberType> m = DoFTools::create_reference_interpolation_matrix<NumberType>(FiniteElement<dim,spacedim> fe);
~~~
which does what we expect it to do. The problem I see with this one, is that it will only work for scalar-H1 conforming FEs. 

Let me clarify with an example: if we have a RaviarThomas Element, FE transforms a `std::vector<Vector<double>(dim)>` into reference `dof_values`. It expects in input the *transformed* (under inverse Piola Transform)  of the corresponding values in deformed coordinate systems.

This cannot be done at the level of the FE. It *has* to happen during the interpolation, so I'm afraid there is little we can do to avoid fiddling around during the call to interpolate, *on each cell*.

**Comment by luca-heltai** [comment]
And since we have to do this anyway, that may well be the right moment to convert to the right `NumberType`.

**Comment by bangerth** [comment]
But the transformation matrix is correct with data type `double`. You may just be multiplying it by a vector that has a different data type and get a vector with a different data type.

**Comment by luca-heltai** [comment]
The problem with the matrix is that its layout is arbitrary, and essentially an internal implementation detail.

**Comment by bangerth** [comment]
Why? Its columns correspond to the (generalized) support points (in the order in which they are provided by the element) and the rows to the degrees of freedom (again in the order in which the element describes them).

**Comment by luca-heltai** [comment]
unless you make a matrix whose entries are `Vector<double>` themselves, I see no way to make this work...

Think of `FE_Q(1)^dim`: generalised support points concide with the four vertices (they are not repeated). The function that does the conversion, expects a `vector` of `Vector<double>(dim)`, and converts that to `dof_values`. To transform this into a matrix, you first have to unroll the `std::vector<Vector<double>> `.

**Comment by bangerth** [comment]
Oh, I see now. Yes, good point. You would have to repeat the columns as many times as there are vector components, and I agree that the way you repeat is arbitrary.

Or you could return a vector of matrices (one per vector component).

**Comment by luca-heltai** [comment]
but that does not work for RaviarThomas... the components are not independent...

**Comment by bangerth** [comment]
I know -- the final DoF values are the sum of each of the matrices multiplied by the corresponding element of the vectors of function values at the support points.

**Comment by luca-heltai** [comment]
correct. 

My point is the following. Generalized interpolation should work in this way:

- For each cell do the following:
  - compute the values of the (maybe vector-valued) function at the mapped generalized support points (depends on NumberType)
  - do the same with a function whose value is one in each component
  - transforms both values to the reference cell according to FE::conformity type (0-forms, 1-forms, or 2-forms)
  - call the convert_*_to_dof_values for both fields
  - sum those values to two global vectors
  - scale the one with the function values by the one containing the "interpolation" of ones
  - return it

the convert_*_to_dof_values could be a templated function in FiniteElement with a different name, that performs the transformation between NumberTypes internally. Say, for example, `templated_convert_generalized_support_point_values_to_dof_values`, that makes the boiler plate required for the translation between `NumberType` and `double` internally, only if necessary.

Comments?

**Comment by tamiko** [comment]
@luca-heltai This is _exactly_ how I have implemented it in #4857.
With one minor TODO - the transformation doesn't do the right thing for 1 and 2 forms at the moment.
(I wanted to discuss whether FE::conformity is the right call for that.)

**Comment by tamiko** [comment]
>  templated function in FiniteElement with a different name, that performs the transformation between 
NumberTypes internally.

The problem is that with a template the method cannot be virtual any more. With that,
`finite_element->convert...` calls the method in the base class and not the one in the derived class.

**Comment by luca-heltai** [comment]
What I'm saying is not to **replace** the existing one, but to provide a templated implementation in the base class (with a different name) that uses the one based on `double` to do its magic...

**Comment by luca-heltai** [comment]
so that the one with double (which is virtual) is the only thing that is called by the templated function (which is not virtual).

**Comment by luca-heltai** [comment]
My proposal, not to mess with names, is to implement the following: 
~~~
template<NumberType>
DoFTools::convert_generalized_support_points_to_dof_values(fe, values, dof_values);
~~~

**Comment by bangerth** [comment]
Isn't that basically what the function in `FETools` already does?

**Comment by tamiko** [comment]
@luca-heltai Externally in `FETools` is a better idea.

**Comment by tamiko** [comment]
@luca-heltai 
It thought about the interpolation a bit and I think your algorithm is not correct. (It doesn't factor in the fact that `fe_values` apply a transformation from the unit cell to the real cell.)

I have written a bit of documentation what I propose in #4857 that is now a pretty complete prototype.

**Comment by luca-heltai** [comment]
@tamiko , I'm not surprised that your implementation works, but it's not what I would call the most correct way (mathematically speaking).

The algorithm I describe is not *exactly* what you implemented. In the algorithm I describe I advocate to transform **both** the function **and** the `VectorType::valye_type(1.0)` using the same type of transformation, and then transfer the information in the same way to the global vectors. 

In your implementation you transform the ones always in a H1 conforming way (in a separate loop), but use it only to compute the weights for the weighted average. These two algorithms are roughly the same, but not quiet, especially in H-div and H-curl conforming elements.

They are both projections (and this is good), but I suspect they have slightly different convergence properties.

Now that I think about it, I'm (slightly) surprised that your implementation works with H-div and H-curl. I would have thought that you could not reproduce a projection if you did not factor the area of the faces in the weights (which is what your transformation does behind the scenes, as it uses the co-factor in the transformation).

I'm afraid this is probably due to some coincidences on the number of points / degrees on the faces / etc.

**Comment by kronbichler** [comment]
@tamiko @luca-heltai anything planned for the current release?

**Comment by drwells** [comment]
@tamiko We can take the milestone off, but what would you like to do here in the future?

**Comment by tamiko** [comment]
@drwells I don't quite remember. Let's close.
