### ISSUE TITLE
9.1 Release

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#8080]
Check list for [release-tasks](https://github.com/dealii/release-papers/blob/master/release-tasks)
=================================================================================

Release preparation steps:
--

- [x] <b>-3</b>  Send out notice to the mailinglist if anyone has outstanding issues or patches.
- [x] <b>-2</b>  Check all issues and pull-request on github. Create a list of things to fix before the release.
- [x] <b>-1</b>  Update the list of publications. (Send standard e-mail)
- [x] <b>-1a</b> Start release paper process with email to all current (principal) developers
- [x] <b>-1b</b> Update the authors list on the homepage authors.html
- [x] <b>-1c</b> Update the list of contributors in the release paper
- [x] <b>0</b>   Do some basic testing as always
- [x] <b>0a</b>  Rerun cppcheck across the source files (@drwells #8142) (@tamiko #8140, #8141) 
- [x] <b>0b</b>  Check for doxygen formatting problems (@tjhei)
- [x] <b>0c</b>  Fix formatting bugs reported by various command line queries (@tjhei )
- [x] <b>0d</b>  Check that doxygen produces no errors when generating offline docs  (@tjhei)
- [x] <b>0e</b>  Run the copyright script  (@tamiko)
- [x] <b>0f</b>  Update Trilinos and PETSc to the latest release on the tester and update documentation of supported version. (PETSc: @masterleinad, #7877)
- [x] <b>0g</b>  Run codespell (@masterleinad, #8124)

Release steps:
--

- [x] <b>*</b>   Nominate a "release officer" that is in charge of (almost all) of the following steps
- [x] <b>1</b>   Create new changes file
- [x] <b>1a</b>  Adjust doc/users/doxygen.html to link to the to-be-created TAG file.
- [x] <b>4</b>   Create a release branch
- [x] <b>5</b>   Update the VERSION from 9.1.0-pre to 9.2.0-pre on master
- [x] <b>6</b>   Update the official tester to test on the release branch dealii-9.1
- [x] <b>6a</b>  On mainline, update deal.II dependencies of examples
- [x] <b>7</b>   Create an AUTHORS file
- [x] <b>7a</b>  Send prerelease announcement to dealii@googlegroups.com
- [x] <b>8</b>   Remove unfinished tutorial programs.
- [x] <b>9</b>   Write up a short release note and save it as announce-9.1
- [x] <b>9a</b>  Write the release paper
- [x] <b>10</b>  Test the branch thoroughly
- [x] <b>10a</b> Do the same for the code gallery examples
- [x] <b>11</b>  Create documentation and verify
- [x] <b>11a</b> Check that .gitattributes is up to date. (Do quick tests work?)
- [x] <b>12</b>  Push the button
    - Change VERSION to 9.1.0 for a release and to 9.1.0-rc1 for a pre-release
    - Create a signed tag of exactly this commit
    - Push changes to github
- [x] <b>13</b>  Create the tar files
    - Download the source tarball from github, verify that its contents is what we expect
    - Cryptographically sign it (detached, armored signature)
    - Create full offline_doc tarball and sign it
- [x] <b>14a</b> Create a pre-release on github and upload files (and detached signatures)
- [x] <b>15</b>  Generate the documentation on the webserver.
- [x] <b>16</b>  Adjust header.include on homepage
- [x] <b>17a</b> Ask Luca for Mac packages
- [x] <b>17b</b> Update dealii in [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py) (@davydden)  EDIT: https://github.com/spack/spack/pull/11527 https://github.com/spack/spack/pull/11573
- [x] <b>17c</b> Update dealii in [Candi](https://github.com/dealii/candi/blob/master/candi.cfg)
- [x] <b>17d</b> Update dealii in [Gentoo Science overlay](https://gitweb.gentoo.org/proj/sci.git/tree/sci-libs/dealii)
- [x] <b>17e</b> Update dealii in [Ubuntu/Debian](https://salsa.debian.org/science-team/deal.ii)
- [x] <b>17f</b> Update dealii in [Archlinux AUR](https://aur.archlinux.org/packages/deal-ii/) (@drwells)
- [ ] <b>17g</b> Update dealii virtualbox images (@tjhei )
- [x] <b>18</b>  Finish writing the announcement
- [x] <b>18b</b> Adjust news.html in the deal.II homepage repo
- [x] <b>19</b>  Announce the release via e-mail
- [x] <b>19a</b> Send a note to the Facebook account ~and Google+ accounts~
- [x] <b>19b</b> Update the deal.II wikipedia page
- [x] <b>19d</b> Send thank-you email and list the people already referenced in step -1b above
- [x] <b>20</b>  Celebrate!

**Comment by tamiko** [comment]
@dealii/dealii All, @kronbichler suggested that we aim to branch out this Sunday!
For this, we will have to go through the open list of Issues / PRs for the 9.1 milestone soon and determine what shall make it into 9.1 and what has to be postponed to 9.2

**Comment by bangerth** [comment]
We clearly can't branch today. There are still a number of outstanding PRs that have been approved but haven't gone through the tester yet. I'd also like to see the various AD patches finished as well as #8072 since it changes the interface.

I've also hit a snag with #7628 which explicitly calls python3 but that happens to not be installed on my system. I'm working on a follow-up and hope to get that ready in the next couple of minutes before @zarestky comes pick me up!

**Comment by drwells** [comment]
I still want to make as much progress on #6774 as possible. If others feel that we cannot review these changes in time then we can delay the PRs.

**Comment by bangerth** [comment]
I'm going to be mostly out for the rest of the weekend traveling to Europe (and then only sporadically online after that over the course of next week). I think I've managed to review most of the outstanding stuff, it just needs to get through the tester and (in the case of #8072) get a couple of minor updates.

But I know that the process is in good hands :-)

**Comment by tamiko** [comment]
@dealii/dealii It looks like that we are on a good track to branch either Monday late, or Tuesday :-)

**Comment by tamiko** [comment]
@kronbichler Will work on the "release preparation" steps this evening (central time).

**Comment by kronbichler** [comment]
I'll continue to go through the open issues tomorrow morning and start looking into some of the test failures we still have. Depending on your progress I will pick up items on the list as well.

**Comment by masterleinad** [comment]
@tamiko Need any help?

**Comment by tamiko** [comment]
@masterleinad Some help on reviewing the last 5 PRs summarized in https://github.com/dealii/dealii/issues/7809 would be great!

**Comment by masterleinad** [comment]
I guess multiple off us have done 0d already. There was #8115 and I also checked. Of course, it doesn't hurt to look at the logs again.

**Comment by tamiko** [comment]
All, I think it makes sense to wait for the CI to catch up with #8135, #8140, and #8148 and branch out as soon as those three PRs are merged. We will then cherry-pick #8079 to the release branch later this week.

**Comment by tamiko** [comment]
Inspecting the tester reveals that we has some major fallout regarding adolc:
 - gcc-7: https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=9773
 - gcc-8: https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=9774
Has someone some insight into this? @jppelteret *ping*

**Comment by tamiko** [comment]
Going to bed now. I plan to branch out tomorrow morning after the last (now 5) PRs have seen the tester and are merged.

**Comment by jppelteret** [comment]
Sigh... What revision of ADOL-C is on the testers? I've been using git rev `caaac60da4c61b370d106c68064d38c42a7cb6e3` for some time with no issues, but I see that [in the recent months](https://gitlab.com/adol-c/adol-c/commits/master) they have merged in changes from their SVN repo. Maybe this broke something? Looking at the numbered suffix I tagged the tests with, I believe that all of the (definitely) broken tests relate to taped ADOL-C types.

**Comment by kronbichler** [comment]
@jppelteret Since you seem to be a bit under-worked with failing tests lately :wink:, I have one more for you `helper_scalar_coupled_4_components_01_4`:
https://cdash.kyomu.43-1.org/testDetails.php?test=64820978&build=9755

There are some NaNs in the output and we eventually get a floating point exception. Is that test maybe revealing some problems with Sacado? Unfortunately there does not seem to be a second test for this variant in some other AD component, so it's difficult to say for me.

**Comment by jppelteret** [comment]
Actually, these three tests __should__ give identical results as they compute second derivatives:
- ADOL-C taped type: https://github.com/dealii/dealii/blob/master/tests/adolc/helper_scalar_coupled_4_components_01_1.cc
- `Sacado::Fad::Dfad<Sacado::Fad::Dfad<double>>`: https://github.com/dealii/dealii/blob/master/tests/sacado/helper_scalar_coupled_4_components_01_2.cc
- `Sacado::Rad::ADvar<Sacado::Fad::Dfad<double>>` (the trouble case): https://github.com/dealii/dealii/blob/master/tests/sacado/helper_scalar_coupled_4_components_01_4.cc

> There are some NaNs in the output and we eventually get a floating point exception. Is that test maybe revealing some problems with Sacado?

I believe this to be the case. I don't see why this should fail (especially if it works for `Sacado::Fad::Dfad<Sacado::Fad::Dfad<double>>`). Maybe if we select a different evaluation point then things will be fine, but its annoying that these `Rad-Fad` types are not robust.

**Comment by tamiko** [comment]
@jppelteret I tried again with current HEAD 558f49ed43bfc3d0dbeefdcf289b5c83209d05f8 and again all "retaping" variants fail. Do I have to configure adolc in a specific way?

**Comment by tamiko** [comment]
Anyway - I think it is time to branch out. @jppelteret We will have to fix this adolc retaping issue in some form, though. I am happy to assist!

**Comment by jppelteret** [comment]
> Do I have to configure adolc in a specific way?

I configure with
```
BOOST_DIR=`eval "spack location -i boost"`

CC="$SPACK_VIEW_DIR/bin/mpicc" \
CXX="$SPACK_VIEW_DIR/bin/mpicxx" \
../configure \
--prefix="${PWD}/../../install-atrig_erf-boost_pool" \
--with-boost="${BOOST_DIR}" \
--enable-atrig-erf \
--enable-traceless-refcounting
```
(no advanced branching, since I don't use it ATM).

> I tried again with current HEAD 558f49ed43bfc3d0dbeefdcf289b5c83209d05f8 and again all "retaping" variants fail.

I'm wondering if something broke in the last few months. Can you please try caaac60da4c61b370d106c68064d38c42a7cb6e3 which is what I have tested with GCC 6.3 (Ubuntu), GCC 4.8.5 (Centos 7), and Clang 4.0 (MacOS).

**Comment by tamiko** [comment]
@jppelteret I will first try your exact configuration options. I had "advanced branching" enabled and "traceless refcounting" disabled.

**Comment by jppelteret** [comment]
Cool. And if that doesn't work, please try the older revision (which is after one of my contributions was merged). This could be really annoying, because I think that they're also either about to release 2.7 or have already released it. If it has a bug, then that will be a disaster for us (since neither 2.6.3 nor 2.7 will actually work). If the older revision doesn't work then I'm out of ideas (other than trying an older compiler?).

**Comment by jppelteret** [comment]
> I'm out of ideas

I could (reluctantly) also take a look through the latest version of their manual / examples to check if something has changed about the way takes are setup.

**Comment by tamiko** [comment]
@dealii/dealii We have a prerelease: https://github.com/dealii/dealii/releases

**Comment by tjhei** [comment]
Several of the newer tutorials are not listed in https://www.dealii.org/developer/doxygen/deal.II/Tutorial.html for the release (58, 61, 63, 64). Is any of those still "incomplete" and should be removed from the branch?

**Comment by tamiko** [comment]
Another point to discuss is whether we should set `DEAL_II_COMPILE_EXAMPLES` to `false` on the release branch.

**Comment by masterleinad** [comment]
> Another point to discuss is whether we should set `DEAL_II_COMPILE_EXAMPLES` to `false` on the release branch.

Yes.

**Comment by tamiko** [comment]
@jppelteret adolc retaping tests fail for me for any checkout mentioned and any configuration variant.

**Comment by jppelteret** [comment]
@tamiko What are the names of the tests that you're referring to? Are they _just_ `adolc/helper_retaping_0[1,2,3]`?

**Comment by tamiko** [comment]
@dealii/dealii We have a new release candidate!

**Comment by tamiko** [comment]
@kronbichler The testsuite is in great shape, the only open problem is gmsh-4.1+ support with some expected update on Sunday. What about we aim to tag 9.1 on Tuesday?

**Comment by tjhei** [comment]
We should do another run through on windows (visual studio) before we tag 9.1. With so many changes, I am sure we broke something again. I don't have access to my windows machine right now, but I can try to set something up.

**Comment by kronbichler** [comment]
I agree with @tjhei that some Windows tests would be great. Maybe it can happen until Tuesday?

**Comment by masterleinad** [comment]
I will try to do that with the latest version.

**Comment by masterleinad** [comment]
I can build `deal.II` using `Visual Studo 16 2019` (`MSVC 19.20.27508.1`) with minimal dependencies (`boost`, `muParser`, `CXX17`).

**Comment by tjhei** [comment]
Same here. No warnings.

**Comment by masterleinad** [comment]
Probably, #7928 is still a problem, though. We might want to discourage from using anything else than `Visual Studio 2019`.

**Comment by tamiko** [comment]
@dealii/dealii All, I have just tagged `-rc3`. I hope that this is the final release candiate. I suggest that at this point we keep the merges to the `dealii-9.1` branch at a minimum (with the exception of a fix for #8245 which I would very much like to see to be in the release :-)).

**Comment by drwells** [comment]
I would like to also get the followup to #8260, which is purely a documentation fix, in 9.1.

**Comment by tamiko** [comment]
@drwells You actually did merge #8260 directly onto the dealii-9.1 branch.

**Comment by drwells** [comment]
It was late and my eyes didn't notice what branch it was on :)

**Comment by drwells** [comment]
In case others didn't see it: we have now officially tagged the release!

**Comment by tamiko** [comment]
https://github.com/dealii/dealii/releases/tag/v9.1.0 is out :-)

**Comment by tamiko** [comment]
Closing :-)
