### ISSUE TITLE
step-50 TODO list

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#8482]
- [ ] Don't use vector_t, matrix_t
@tcclevenger: Seeing this in your talk just now -- we generally use `CamelCase` for types, so seeing `vector_t` and `matrix_t` in step-50 looks a bit odd. Maybe want to put that on your list of things to change.

**Comment by tcclevenger** [comment]
Yes, I will definitely change this. Thanks.

**Comment by tjhei** [comment]
- [ ] more interesting problem
- [ ] test with PETSc and Trilinos
- [ ] "some" scaling results (I can probably run on a big machine if we are happy with things)

**Comment by tcclevenger** [comment]
Is there any objection to renaming `mg_dof_handler` to `dof_handler`? I think the name is confusing since `mg_dof_handler` doesn't only contain MG information.

**Comment by tjhei** [comment]
> Is there any objection to renaming `mg_dof_handler` to `dof_handler`?

good idea.

**Comment by bangerth** [comment]
The name `mg_dof_handler` is historical -- we used to have a class of that name. There is no reason to still use this name.

**Comment by dangars** [comment]
@tjhei I would be interested in running step-50 and geometric multigrid with PETSc. I would be happy to contribute. Could you let me know what is missing?

I identified the following items:
- You use `exchange_data = true` in the function `reinit()` when you initialize the system_matrix. The interface of PETSc does not have this option. This option is not used in step-40. It is unclear to me if this is important.
- You use Jacobi as smother. In `mg_smoother.h (line 1169)`  you have `smoothers[level].Tvmult(*d, *r);`. The function `Tvmult` is not defined for `PETScWrappers::PreconditionJacobi `. But this is straightforward, since this is a symmetric preconditioner, this function is the same as vmult(). Happy to submit a PR.
- You set the relaxation parameter of the smoother `omega = 0.5`, but `PETScWrappers::PreconditionJacobi ` does not have this option. I checked the PETSc documentation and I couldn't find a way to change the relaxation parameter of Jacobi. Is this strictly necessary?

Am I missing something? Let me know if there is anything else I can do to make geometric multigrid work with PETSc

**Comment by tjhei** [comment]
Hi Daniel,

@tcclevenger and I will open a PR for the updated step-50 version in the next couple of days (based on the version for a publication). Many things have changed compared to the current version on master.

> * You use `exchange_data = true` in the function `reinit()` when you initialize the system_matrix.

I will fix this (the call to reinit() is just slightly different).

> * Tvmult

Would you mind submitting a PR for this?

> * You set the relaxation parameter of the smoother

The updated version works without damping, so we can make things work without this for now.

**Comment by dangars** [comment]
> > * Tvmult
> 
> Would you mind submitting a PR for this?


@tjhei Thanks a lot for your reply.

I added Tvmult to PETSc PreconditionJacobi. See #9887

**Comment by tjhei** [comment]
> I added Tvmult to PETSc PreconditionJacobi. See #9887

awesome. This was all that was needed to make it work!

**Comment by dangars** [comment]
Happy to hear that :)

**Comment by tjhei** [comment]
done, closing...
