### ISSUE TITLE
FEInterfaceValues (meta)

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8884]
meta issue to keep track of the work as the PR #8541 is now dead.

TODO list:
- [x] base FEInterfaceValues #8660
- [x] ~~correct behavior on boundaries: #8706~~
- [ ] convert step-12 and update documentation #8661
- [ ] extractors
- [ ] do we want additional functionality liike get_function_values?
- [ ] DG laplace example
- [ ] Stokes h-div example
- [ ] test GMG
- [ ] test MPI parallel computations
- [ ] extend MeshWorker::ScratchData
- [ ] higher derivatives 
- [ ] benchmark against meshworker
