### ISSUE TITLE
Python bindings for pre-/post-processing

### ISSUE THREAD

**Issue by agrayver** [dealii/dealii#9015]
@dealii

I have decided to turn this into a meta-issue that will track my efforts towards a better python support in deal.II. 

- [x] Add support for faces and boundary ids (fixed by #9023).
- [x] Enable indentation for python bindings (fixed by #9028).
- [x] Add interface for mapping objects (see #9055). 
- [x] Enable working with manifolds (see #9109 #9179)
- [x] Extend GridTools support (see #9148 #9178 #9429 #9510)
- [x] Add bindings for Quadrature (see #9428)
- [x] Implement tutorial programs (candidates: step-49, step-53) in python (see #9526 #9777)
- [x] Avoid duplication of the docs by using *copydoc* (see  #9668 )

If anyone has something to add, feel free.

**Comment by agrayver** [comment]
@Rombur I see you already implemented merge/shift -- do you see any caveats for other functions?

**Comment by Rombur** [comment]
Being able to do step-49 in python would be really great! I think that it should be straight forward. You should be able to follow the recipe used for the functions that have already been ported but let me know if you encounter any problem.

**Comment by agrayver** [comment]
I would like to consult regarding the nature and place of the new python tutorials (step-49, step-53 initially). They will replicate the functionality of the original programs, using the python bindings and will be presented using the python notebooks.

Should they be placed next to the C++ programs, in the corresponding folders? 

@Rombur @masterleinad ping

**Comment by Rombur** [comment]
I think they should go with the other python notebooks in `contrib/python-bindings/notebooks` and I would add a section in the C++ tutorials that links to the python notebooks.
